mysql_prod:
  host: 1000af59804227d35963e81860c37870d29c0635f3b8e7a6a3031b4abbfb4dfe1d08
  user: 1000f2d08c89132bb4cb12316924742015bb038e781236a73933ba5b73550c033295
  password: 10001347c230f954253fc8601e86d4000bf27931e941f10ec36e168f7b37163e5bc1
  user_read_only: 100018a15a632db009494a174112e1ef469ec2b5d8772e87342d5a7824ac5cb7489e
  password_read_only: 10009d0950398dba0d6686f426f6f7e6cb8da89b0e9078e89574f5651cfb65d007ac
  db: 10008dcfde19c79d1e9acbb5a55fac75710ac719ee875acfab8fa2d36800e5e61c56
  port: 100039dab7fbcd4ac968017983a1e1e5be5bcbaf5ec8a4c069c07601f63bba859fb1
postgres_prod:
  host: 1000218b47d48d765f3a868fc6e3e150924b3c73ae4166e76f74454d82398365f3cd
  host_slave: 10000f37c8a5d5d68d59ee7643b5da02ad75ca5de254fdc06b0c44543f7fcdf8505c
  host_statistics: 10007c65e95d229034e72822c37ca3daa511e6ae68332216d69c5d43c8c103c5ae3e20ee274916c6e46898c1fed57152d4ec
  host_legs: 100007967e8a52ea66b69584501c9fad96b44157ac12405fa50b38a48336123faaf60812707d1d3c659886da4eb03f76d03e
  user: 100083122a623b3a431810375dc4cf4800d81b2e5219bfe01af55534d7a582c62adf
  password: 1000abfaa332f8d4793c28e92159a046e44d9bc0be6dee86b68157bcc32841b3cc8804a359e05dc15540189f90836623456c594db8b597e244313132186a171d0697
  user_legs: 10006f89642a16db0a7c9b1f658a3be85022c5f8439e18df5d20175572970d122d19
  password_legs: 100091ae5c21058b7694eb6109cec6ff1f6ce6abf5132e09651d1c9901d59cf7699a
  user_read_only: 100063c19d8120ade94f81b2630e8694307f6c178f4da78d3800d7fda700b777155e
  password_read_only: 10001a162b1e672e26e208bc973f7e0c7cabf108c24e916121fd7f83691d90144f71dcabce7f202bc99d5fb6401498a0ccd6
  db: 100033d42c43b20a188a08d7ca6151c231a7d861ba84789dbf2587fb7ba9457ba9f8
  port: 1000768228fabe27e211ccec5cc4b11debf5fb9c0a4cab833450b823f648f7e22e1b
params_prod:
  api_secure_key: 100059c2094b1f225864d5d3def15e057752ed2618388ed890a168857aadd12b3b9a2027908f4e5719bf2a5bdd25ec42e4ae
  token: 1000938977de556530d726f3e4d29a4a3371232350960464c580d6f6f1804c79f25725e0c2814253d6519f0ac5cdd6fe14167fd1603a6a6f2ac85823166ec61b34b4
  feedback_api_key: 10007bed0aea4e259f9d35393a3b993d96ae6968dce5af2f93d82feef1e7c8a4b094
  mailer_user: 100062ab6a90b5952a1ec8c445b080242ffbf72fe76ed0e0eed391b51ad1907caf85
  mailer_password: 1000e77600b47edeaf401263df83f895ec6e99e96686c65394f3e214a4675755a97d
  notification_token: 1000fe2377a3c2eba9dde34489ababe163eca453bffcd0e37f6317b4e5a1fa7cca158223e123769826d657aac0540ba8d40d
  sms_client: 10008548f27900df5baacbb59c1d45369262e6d7d1708a7875275989d8f36486293c
  sms_password: 1000415dc56a3df7697484ee7e58026660bed91e4fc272a412894604113ad1659607
  monitoring_email: 10009ae18887cf857a6deb30017e980ea8041403082366a067a3b8ba31c4be8f5e1d
  vps_authinfo: 10009f6118e00036e979549732e844c0532049261c6e05ff61a9d2085e988cb56a42eab1fb30eabda7dc97aa4d2b397cea1c
  sberbank_api_sberbank_telecom_user: 10002c92fbc82af8b2e189e3bc47aa2e9d172a9e7b83bf7f42bd8385bc3aa1f8f5b9
  sberbank_api_sberbank_telecom_password: 1000dc185d41abd4faf3ed535c45b20e8a5a28b85ca619b55b7ccf192f3b4cf7cf94
  sberbank_api_sberbank_retail_user: 1000d4136dbcb9ffd2bbe8d5d83a9176dacbbc7c0eb223ffd8ee0b6d13edb6967949
  sberbank_api_sberbank_retail_password: 1000a87ff253ab67048cf3e487effcd89195170ba8c906be8b3f1a2ec0409d540ca0
  sberbank_api_sberbank_service_user: 10005f20081316bb177a8eaadc8a6eb654a3ec798ec763a302e95f74fe74af5c4d2c
  sberbank_api_sberbank_service_password: 1000d9d974d23e9e5f8933e3866e65670520b2fd67f92a5d1f6fcfec501142d80ead
  paypal_default_user: 100008c1bf290a70c12b3784c74e5edfc3b675ff41055c509804d1401fa532ef394c2e60c6cd00e1429367ad8963c911a9e2
  paypal_default_password: 1000cb61a3449d9eac6b2f4bd7709a3d11f319c1651996f19ec686fbb60296b0d416369bc446f457bcb3fab29e62e4d5b2e5
  paypal_default_signature: 100037a73a0e2ebcc186cf8028413425c51d8211255ee625cd9713a6d8e196afe876351fdb36923a89acb416c4fcfae0e93a4c6cc82f48de171d019630d31a0ce7ab1798bf032b8d2c17d8df758489a0f0ac
  paypal_tel2tel_user: 1000b82ff07f1845148ee2a0398e2c872aa24bf3c04687f7861fa887b542d8304dce0d520cbd2893ae9d69c1915b9c5fa003
  paypal_tel2tel_password: 1000d0265ee870fee6fbeeac890894bf1781051f2a0227e547ae08228b4860be52a11a1f878aa3b907026771a2bccf2858e1
  paypal_tel2tel_signature: 100095c81fb50ca94f39133c1ba02a33cd218db906ca285c67458be42e9636a930c732d47e5283fe0a71c3ce314fe56f3edbcec47ef82feb186273414ca6c5b749abf0ed7b629669f0b76c3156df649a8fd1
  yandex_kassa_telecom_shop_id: 1000edba08a5f6a0152d8588d6e0d53ce8579e02c3d1029a5d0cc97f9fca6a913e91
  yandex_kassa_telecom_sc_id: 1000a1af9930aa0dd9ef75de7caff7e8b2401aa43f4e6d5a24a4ec017ac25937c9b6
  yandex_kassa_telecom_password: 1000cc9239b70abf03fd0041e1ab70459790c37867691bec5ef51ec61752aa39359641e074f4c0c9f3767b09aa832c267f2f
  yandex_kassa_retail_shop_id: 10001ee7327d5905d0ed0e357383ed6c4d4180df99acd817a31c7a860af12b750929
  yandex_kassa_retail_sc_id: 1000bb2119e22425cf5b1e8650c6b0c4c007f4f13a15a37168c87abd6ab1688d966f
  yandex_kassa_retail_password: 1000d4a734e396911367af62878427ee1a70809a0f1842a1b6dc9326f37a8b28ed6cf21ea3fb21aac27de71c21d63b8acc71
  yandex_kassa_service_shop_id: 1000d37fc7c0953b2ae4b96bade1bb3b5f15e80502e2f8c527bc322d98e368b644b3
  yandex_kassa_service_sc_id: 100025f7c761efbea480ea4116e3930273b3b86d801cfcc706b9a6690b6e02a90caf
  yandex_kassa_service_password: 1000f33dbd077869bf711ce105aded37c9cc4f6e8c917f9695c8288839cc43930c98938bc7a3689938c782374bc49118c83b
  rocket_chat_token: 1000bfbe47f284b5b63ba5057ad0e58275df2142a0fb9130e33a5f7769c039b85bebf5e9266d4e19ef35a6bc6a6195122ba04acb96b62ee3ffc1c307c59c7e51cd6a294ef8ed7f806980323332b8e21c76b36e4e8e4a89d5c14874881b7628f4e5a5
  nnp_info_service_url: 1000e586b5add9438463980c4a8581999ae02cd595c96ac687821f4c88f6c3239967eafb78f68ff455311f9c2a699baab7ee898b79803eabe69bdab9781e5d232001
  biller_api_url: 1000906d9479799de3b59f36b3911b8b824014fb914127a51f70482749920e999a4755823c32b0276e8e86342064277a1b29f5b1d56625c403d277ea451d5f58c44c
  client_changed_amq_settings_host: 10001e8ca9a770394c22fff912f46605eb1e24921744d93e90b6e0359600e5654226
  client_changed_amq_settings_user: 10001e57b51b91f301786ab11d774a659d2fdbffd49f8da3bc8cd351ab7136d21c81
  client_changed_amq_settings_pass: 100018e8c18358db6f18829cb258c17b3e3f843ad79417cc7298ec6a99f829a1ff6c
  tele2_amq_settings_host: 1000b44b11da93ef12da85f35caca3a9df8c7cdfdbc0dd810f25361d32fbaf29892996f01c977ff42679110f69364563bad5
  tele2_amq_settings_user: 10001d15da45ac6666942e1a3393b6c6c9fcd2d24c6304dda101365d9b8568033fd3
  tele2_amq_settings_pass: 10002043da62881ecaf218d8310fec0db91f739b24962e7f3888c803567424d257cc
  robocall_auth_token: 10008897e2373c57b1c60366b19a1e9c82923a59b3a21f15bcacfbed5a142b027b97bb621b96c960f5b5f1ab21d4ba425d20cbe576c6d5073cc20b7d39e9c0876b16
node_comet_prod:
  secret_key: 100046e6f19ec9bb6d4f3df513defb7f93f79a89b709f74c309630214fe7c9378b72842420302c22682818550c449bc54fe4
node_nnp_ported_prod:
  connection_string: 1000b28ab41a7db1337c424b451595a938fdc4538209177acc6e638cc9eabb6196c2d4681cd1d42b9f2c6da81dd5520a375107134edeed579cc74e50d5081ceb66f7857d4b6c8374cf066a9ce7c08ffb8211
  get_url: 100090c64e2c3eb73dad953959dde2471ba44598c184218bea6d24009647c4d87c63126985ebee692cb2b3d77caba4fc8b1ccc31d226cc24330d468f2517903a7c5f356336d07f7a2c709d3c1716474d0c1241ff20ad51b2aa60616937cb36a52b23
web_hook_prod:
  secret_key: 1000e5ae72e9dfaab4d5c35b5a0444b0d91ce77e8503094d938c6bcb2671f8101d9772135576184b9d84a689fa0b0980ef405c18af5b368ac7d979cade2ac55edf18
  token: 1000ab183a6aa6a7dc47a63fdaace49d4bc100923f090fe6f20223319e680fe489bcd9e203d1594611bc6295122c898d6710e543e1dc87a2c64ea8314bda634a419f
  account_id: 10000e48aaa5ee8c64fede04f84b24d1b7eeb21788d8a10d8755e76d2bc8812d387a
  vpbx_id: 1000c4889d6da1a3ba213372b364a7c851b9bad2777f91a16ed7b514adc81586d2cf
payments_prod:
  user: 1000218186c6b33195af0e0bd061446c6b89a0d6e7746ca58a3ba369488e143a2dee
  password: 100001e7bf14684bce5740b1e0a42009d92ea08ce707bec42d7217f4d8079e786e27
  publishable_key: 1000b83eccb112de2124d2329d0fa7d0dcf65f696a76cc3de644ac4d6bf65c614729ed5a3437f6f5538e863607f1b7fe8d31a8b34ac944390957849be5b25be0273c
  secret_key: 10009fab7392e13cc05a4b2a9cb18095df312a60ea128b1f58e15ef2e2a1e56f9a35045fe1347b4351ec349733c0f31ef5e77e00962e3ef65014d90304dddb32f4bf
nnp_prod:
  numlex_user: 10002bbfff12dc8645ef5063b15ef110b921213130daa7b0a9ffabaae96f97b48d0f
  numlex_pass: 1000998915791a23c7459c8a89dbd5b09d4e6fc1955c7501a269b8baf62a51b27148
sim_prod:
  authorization: 10004ca58e1b0f8da5f2f68c7162488016e51cc172d7654ebf1cce4522457376d8f00efbb49fa52e4fa1177ef03ade4a09dbfc3f871e17867b51ab91871fbff36800
  transfer_msisdn: 1000f76a1dc8da79f016042ea1bc0e0dc4aad6c0224506c8b667953a27880ff42849
notifier_prod:
  uri: 1000a357231e98fc2f1d8fe58727b6f416de1c3026db3f587fafaccb50ea1ab43a37aed41abc459cf8b3b6a8f15d87408696
  user: 1000f885e837452f5e465cba47ed848711987ce79731935d7b983d76c03a407bb9fc
  passwd: 1000617ca27e8bb0b5713c18606e17258af6426bd470eca3360e88cddb4e1f8b8e4c
atol_prod:
  call_back_url: 1000754aa8e59cd6840aa22918708f86b121a25a081d917d5d78a4126109ebd51fb54130505e49ae446946e69bfb03118c34
  access:
    mcn_telecom:
      password: 1000a6021f5ab6e620e6b2de20b30ea8f7a43587b591d4767d85e771d38a2ba81c64
      login: 1000efd47faa92e80518a99279dffa6101d852007c8649f0e47d8d73025a62c5f09e
      group_code: 100003c06c6d6c7d871ac5df9293b4c4ecca0298cca8d393ee7acf657a8d745eb217
      inn: 1000652918fb12e7443c10661fc2629562acd58aef9c27e6195422dcc6e2fe95221a
    mcn_telecom_retail:
      password: 1000550524e55e9a9a02f1a7f39be07fc8e5fec730d8ffb84cb4f9a6b6bf4c7b2504
      login: 10005b9ca431e04b4eb81eeb92faf87afc3b15ed9bf09e9fe3e5942a314ae36b2b86
      group_code: 1000e57a1d5aa0db037fb65602bbb4163bc0ebe82e0a1e3a47be947ca68b95032218
      inn: 10002b14c40ec6bfbeecacfa067829e78898e678132f1c024a9f5818319a47060438
    mcn_telecom_service:
      password: 100090f4212a6f9bf56fb43c134b092b0b9556115d8d5d700ca03c6e1b0d21124d43
      login: 100056851edcd960ddf185a291a6695c4442d27583f41c933375fee6959ce944ccad
      group_code: 100010b21edcc59089ec848fc67b20eb2dcd9870829baf2b217570b42b248b673b65
      inn: 1000f261223fa4acbbafd765c29f2f41b5c1749c896c1880a12da14af0f525ac0fd8
  buy_or_sell:
    payment_address: 10008fb47d4485d85a80c302ebada6e6fc4e670afd1ef22e5d8088c2262b193ebb70
    sno: 100026d4b0bca6caf7d8dfe49e3b1d23ad4d2737f114fc87acf90d38377248755efb4829c7e4feae52fabf9d964a39cf96f4
    item_name: 1000f5a6a7f99b28a05cae519399ea3a3b5a222b39d256128778269888c4d6389d299014dd62a4e13ababdc3d810e033ddfe
    tax: 10007ae77bf4296d82c6c4ee7bb5c006efce65b2239d4b90993fb8895d0425d897a2
mchs_prod:
  api_key: 1000e0b8ec90de1f6f14aaa4098bd5f8323a756a718eb634498ef225cd6fdc5efe6f194b5eb1f3378f49f6fd3ad33bceb95b7439a18dcf2cdd891f5cc30753189461
async_prod:
  host: 1000eca181e3738b212eb2fd590b3da0fc203d1b94cf4ee15adb4309c8e2a5192db8
  user: 10001eeebf7c6392d784a5c5e3d29dab529e8857d6a7fe54d54cda697e2db887dd51
  pass: 100000856ea7a42a5367079dbfc7c8df0e085ca984d1df56340c9f8c18a4492f5bb5
sbis_tenzor_prod:
  login: 1000743082a0c8ecbf29cdc876275d045c4f6a16c98ae43adcec306aa63a5154ee86
  password: 10007f87977cf0cd345ab64ac683cb2cc16165809201fdaf7afd4fc2dd5ebe844193
