mysql_prod:
  host: 10000bc7c0873e7ec26af5a27e3b7e6959eda944da51402a608c53a3ea4c409d3683
  user: 10007d8f4686ecdfaaf5417c2ba5c45967dcae7e674456b78eb3a07f49fd752cc60c
  password: 1000c4148bfe59fe82eca9da3408fdb1a49841dad351e624a5f5d2cd7e83c1fe04c0
  db: 10006197d3ea0ee07a622b76412f22ff9ee026bac1b1be54b7c706fcb637ef8e98e4
  port: 1000369152d4d792aabc12336925805cc387f5525d35b00e6030d586452fd1a60ae1
postgres_prod:
  host: 1000fe8e88a7c27be68e2899c780314e35c5129abbf9f1391eeba158e93b0d5fdde7
  host_slave: 1000cb27546359c674daa302e7f153648f2b5be3aeccdc5c3b190eb4a03f73aaacf5
  user: 10005ae203fb0bbb00cc2caed7d080795c19eb56ae36784c6f833f72e6c11316d991
  password: 1000384a7159e8072b35be3a352b1f60dae8437bc1c2a7e9ce0749319b8997d26f24303127fc24e4ddd3e362a77aca0c4170d0d844f0f587fd31862778b4168be43d
  db: 1000cb4fbbd28c49440c41bc98cb84faeec2565787d22f27ad909f9ee115a84e2702
  port: 10002674b6d840fe18e1091346af6535fc326e0388d34c85f1e6753213ea0846f4ad
params_prod:
  api_secure_key: 100023a02ee1a1f5926a4460f479e74fbafb06afa3501abb72e916ee99fb8e01c13f65c1fa5b0126efbbc0d760cdbef584f4
  token: 10008a6f0ba1225c908479adf5ff61666a03230c63377b6c9743409c53f854a778f12a40436da9a61c459a54f8de1371f4858956e0a45f8daf18641110a77a801417
  feedback_api_key: 100010f46103ec6c7bf1103563bd629af25195f4e6db09c1149ddee075ad4495dee7
  mailer_user: 10007b0a8d356c4621e618cfaf5cf42a2e5d9d3dce3ae66247db8369ecd45b5c548c
  mailer_password: 1000243bbe6f1c0f3d6386352f97a857dec08b52c9599f097caf64194260d86d0f97
  notification_token: 1000dad1c316cd24ebecf585831ebe7bfd20d0790b81c8526f3f3454a9b5a00260e44207d9fa8c2cf2aed44664d4e5aa2cdb
  sms_client: 100099fe647c2bebe5534c6bc1eb090bd6166edd17e5bbca99a804b36e0948fb7477
  sms_password: 100094c4c79055c8a39212ae5a7241aee067914c3e3fc9a36b6ad606e74e05883fa0
  monitoring_email: 1000c979613cb11ec4d3d60e6e1e6ef068c6941c893cf7ff248bac4dbaef4a4e57f9
  vps_authinfo: 100090d64b7aa0160600197fe2e38c031dec315aba898aa89279df23b6f2afa4222aa8ba374acc4c8d5032629639501ccbac
  sberbank_api_sberbank_telecom_user: 100067d868da0ba46722d1cfa72112e7546828780800ef9fca7fb0ae65073367384b
  sberbank_api_sberbank_telecom_password: 1000b34aee057c65259b05178e5f28f5b6b53c19cf7c4b8d194c25eb2cf74901fc5c
  sberbank_api_sberbank_retail_user: 10008daab78f860ed7d9a54d3d66470abf2ed38239e462e012f7b000f1898653a7a9
  sberbank_api_sberbank_retail_password: 1000a177486af3423009bb067a214ee849247f63e07fe4d13a0af0adae2bac5295ed
  sberbank_api_sberbank_service_user: 10003e39a79c35a66703876e111e9b0b43f45b4a332e3a194c47f09760556d54fa3e
  sberbank_api_sberbank_service_password: 1000561f4f29d09966a6907810ee5d4ab5de0b6cd06bac783e9c88a65cc9a7fe60f0
  paypal_default_user: 100046e6c4fd22ae865663edb05213a141f2b24edb123642d6150a403eeb8bcf75dccb5c4a403b87d2dd7cf386d3c37bfdf2
  paypal_default_password: 1000520e40d3c75b1d729af929f46252f870cd4c36e00c40cbc4f0cbf79df7e77d9bbe579bfb9e20dc4a8d44cc32143ed7ee
  paypal_default_signature: 1000606e1c6b6a0bd79796d19224cec8a2f788e301b313bf33170410598c1d9ba2e480d993c3bd88e6d9f30740869d697dba4402b92519d25bf2422dc624e49c5d5985d4b25544bc5c3703fcc5053a458b09
  paypal_tel2tel_user: 10006afacc742bd4c55f95bb25ca51672ff6714abc5a6ba6468e07188c635c636423428e7bc9b6cb2912e0f69a712d3ebe64
  paypal_tel2tel_password: 1000681ce9ce4b532c8249fbf3b662a304ed1d42781ecbaf1234b5e7dff76ccf4fb7f2e481a717fe646438b3deb9140efb61
  paypal_tel2tel_signature: 10002fbce5636d696977590207cb3897546679a35723443b2805c4b19397e7249297ac7d84ee5b16fdc83d88e4b4747a8bdd7a8f1160ea0f65821aafb7511d8daa696fc4fb98e3b917afcf598ee3e6f0da72
  yandex_kassa_telecom_shop_id: 1000ac8ef4846ea342cb89f89da2d748c74473954f8fe3f3fd693b3b5c66ff8d06b0
  yandex_kassa_telecom_sc_id: 1000989414ba16a75202690e3aa4ff57f62dedb6503c4c1ac767871aaeb9cdc14b9b
  yandex_kassa_telecom_password: 1000d043406b7bd869bb9d139c783680f7a7bc63d560469b8ad872ded7d1128619697f7584b70b754f9f8b23619bbe61b4e1
  yandex_kassa_retail_shop_id: 1000740c1ceabcbea7d56ae415ebfb74df08dfe8f545b4e666b68ce973618b247f9e
  yandex_kassa_retail_sc_id: 100073c835a8fccecfd03a492c8cc4d6407fff0a9cd6a83a04f571dc86eb8eba8f94
  yandex_kassa_retail_password: 1000340597b289fb25fae77613a021898fc33d3d5e46199a1b5cd98dc951319ba0ca9f679016a0ec5e2fc9c4b014f64589c4
  yandex_kassa_service_shop_id: 100037d99f31700a17d567d746c7bf92ae2ced5e32276c90dd66f4a849833b2610fa
  yandex_kassa_service_sc_id: 10002f4f27518c234fe7107513f07d0355106e3b345d016e4a3d341e7c50f8751c6e
  yandex_kassa_service_password: 1000b6af5002a61874d0fac9b43c259e2820ded865c6a8db7a26066c755ab8bb11440ac2a9d2025798c17cb3bd2d64328049
  rocket_chat_token: 10007ca097e19ea7816ccc5c5b8f841748fae89f0e6848297731e42d7664c11176cd11471808142f878d5aa2eb5d5b0c20d58e1bc720eb3fbd0ab28230e448820d3d38a9dfb03303a7873eabe3b779731c91511fc5d391cd9dd7ee41f0cca264b287
  nnp_info_service_url: 10002fd8a80a58cf109deef5cc22ab5fea574d3e4b0527d611c192fff8fcce98fbe6ac7b46f65ac309bbac4a7307a861a3ca0b511fba8ac21bfb122815f1ddfbd2a3
  client_changed_amq_settings_host: 1000f8bee661867373039d12c9722f09426f1239f81952ae010ea956bb55a2fb96dc
  client_changed_amq_settings_user: 10003e2708ac8a46b51ba8277ac9e344a04def34191d87b870f28245d40c22433d72
  client_changed_amq_settings_pass: 10002dc13d351f163e05ef2e417521da2aa692d98d8f7d8582d9d7ad1f699bb85ee6
  tele2_amq_settings_host: 10008b598ecbfbefa842c097cd1b3a5cd21b5bb0f10d50bb4fbb0ceff7147d91ca52f680af50bfd112c5a4db82b28b5a65ec
  tele2_amq_settings_user: 1000c60366568e6e3cb4ccd62556482222b702e21f4db3b1dabf9f2dd3a09a4c4180
  tele2_amq_settings_pass: 1000edd62d486167138fdbc484d37c419715339721112980cbf27384f6395df66f9d
  robocall_auth_token: 1000d32b5298b7c7eea456326d859de5f76737e123d3fe310631c09bddfa55d07fb20e30307626af272524bb529aae1deed393f31591238b1d0304266b070269981f
node_comet_prod:
  secret_key: 10006d85e7c26e2da0e82346fa8d64c585274ea28165ba1aa55865dc92d0e91af48dd288fbecce5e23e0c7d234e0e9e61cea
web_hook_prod:
  secret_key: 10005d0df7af907dc8b4b98d4b9cdf57f19f4c30fa04ca0c0cb89ad0355d55acb3671f323693d87888e5d6364b9a1f8ad8c29b681cd65f4b460b8d0a90b51c7320f1
  token: 10005ecd6f8e2295a54628e065cca487cb93c91dde1da64da627e6f15becce1cfdb9e6b815b965db59288d33060325d16fbffc3cb5094939c1a654290a90c5b1831e
  account_id: 1000c7e2c445a02c0a2921ea73201912b1a49812b8c2fb8d72134d551316cb3ed644
  vpbx_id: 1000f8aec7fd3f8d33d2bb69c9eaf86a119bee86a3d630c7c16432ddf04e38aabf46
payments_prod:
  user: 10003e0868a6cc9f7f7d94d47d14e7d2948576da9fe709416c438960fccd4dfce660
  password: 1000ed5c93bc2bd1bd171ee12adea45c6eb3641a597d1fd59146b302596ff22f0cc6
  publishable_key: 10006416e0347f6a7e6c552f32543922a23873810bcac378f5bc73d27c0cc4510e22f718d2a8b54d216911d60583cd6392460b8c120db7867e7401e612ac3d3d47f2
  secret_key: 1000508f5d7323d3f7b4ebc03d4e79e9c8473ec578499b3cf2d1323743be7123a0405251bd0566e476288fb17fde5031ef90e91e8998acabaa69152200546a3aee45
nnp_prod:
  numlex_user: 1000eb3acab5db0087d08b1547f956ca4f89f6224f6e15b1bf63a0922c2ec667d884
  numlex_pass: 10008a0d1a696593fdc0c2cc8ae909dcb90c8b0c8b6f24d42afd5fc375e9c650eac1
sim_prod:
  authorization: 1000bc90fead5938fc367c8a1f8917b480857953cac84671c26205ec77fa251989d6e3b09b64abd55149134dc2b5450f5cb86cd30157ec585ecff3876f49afb9540d
  transfer_msisdn: 1000a0ff9f60cade677f848022c4d91430b374f3ca723f18fe0fbecac6deff491199
notifier_prod:
  uri: 1000bbd74b1f372a515c31b5d5fb5e9db7a7aef44eefec776c458fd4dc163887287aa2c9c6141cf7fe68bad59fb89fc0c8d8
  user: 1000f1e4e6855c4e153f025ee4aac93f1ae7b568d02c5936c51ab61f1f4edb0385a9
  passwd: 1000e52c6ad4aa49748bd46e610da48ff64744a86e75d7ab6bc91658ab3d103cdc3b
atol_prod:
  call_back_url: 1000c6eac48c7f5c6acd07326778cebfdfb8799b4eba03ea90d34ca97de6a0e89725d54041e038c4864a573ce0cb70d75697
  access:
    mcn_telecom:
      password: 10003d5a3fff72100e3a20a4bbbc99830a16f42b95f650c885e949cf3ee22e180317
      login: 1000d87d149b4b3e8b7876d24fb7bbaa6a5f8b2fd7b3697b194cba0f948b2fd3b7f2
      group_code: 100099c8036eaf1ddf2f35deb691cf9dbfd1a85c1827759f3a04da6158d138fe11fa
      inn: 1000e1bc54f3eb8f92d4d1314939cc8b66e52e6566eddac8f1d22c8dea93ab262bd5
    mcn_telecom_retail:
      password: 100076904f8f74dfdafbfbbebce8644d13b7f71652811de270bd9f40e57140d1b2f7
      login: 100044d4bd9d48907c17f493980896ec6faa9c673b9836d72c0e982a9cd1d180e77f
      group_code: 1000a7a4fd3fc7dc6928a708cb568ec95e9f90f256a5102a3eb93a084e41f24fe3f9
      inn: 10000d5a12ff704fbb34f17ee3b04382fa37c91b752a448d4c803cf9f95503437421
    mcn_telecom_service:
      password: 10007668743b5cc9dd4362910e25a2870246ae7c6b272c00a8295d9b6940f1f1e374
      login: 1000d12bde3f53a37ea24e0073c5f0c5d5b8f7ea4fc10b168bd0e43131b9cb80f038
      group_code: 1000e83ce4e79e4cdfbeaa689abab4248c903a4b894120c9a7af6e19bffcf98bcf01
      inn: 1000758e57efc37bb005c2f1ce453817a253c478118352f25dc636f91c30fa181620
  buy_or_sell:
    payment_address: 1000bbe426aac1d999d0444d91cbac400bddffe5812e2d2942402248916ec5d546e0
    sno: 1000fd0903a8813af77f452ecfec1420062bd7fc40d345918abf3d738db30456b56159b8c50136dc5ed48c3184ac33bae48d
    item_name: 1000493b705c6bfc20e3a93edef365edbbd3f9889d53f1acfb3597232f8e1092a5c2273e8df651c02ddc8bb07d1869004a1c
    tax: 10007ed5f4c542c94a3d134ddd45c4388a95d5b7bd5ae9e48e120e9f3289a58c9b86
mchs_prod:
  api_key: 1000f96a5caaaad8ede95195df8f2e3fe30766f47099cc9ac29c6f83b7f239080f0ce6be8101f26f086a7aff1119ad5e97450ba09a601159143746af34ca892d07c5
async_prod:
  host: 1000561eff38f1c6738777808f18ff93662b766922e54ce893343819775659f12b04
  user: 10009b6a35c88a71bb899632a64055dfcf31cd95fa617a4f5a078b7ee92900bb0e70
  pass: 1000db664642b330f7b3c94fe20c3a0111be7eceaf4fe77d8bc6697edde5afeadacb
sbis_tenzor_prod:
  login: 1000245b798a1f71a2b23a524f11551bb9a0fcf817d2280e5ca6fe14436cb2cc5be5
  password: 10005e48de576ce0c7122b00b3c05324e4a238317c41929ec585b1599c9cda654a6a
