mysql_prod:
  host: 1000ecd6258713cbaea83016340ad9f2dbdba4e6ea6dbfab17b32081978e9016868a
  user: 1000813aabbe465cc39636c671652cf8274197a3453ac04dfcf50fc9dbd4d8c40723
  password: 1000f8c8229d74ee503cb77e8c30d6987ebbaa9da197041bff00b0771012426ce5c8
  db: 10001390eeb33eb1dffc340ffefe1fa8a74166628375f4142a0ba1385db648f7ccf9
  port: 10002231f97fd331bf11d751cdc5ee64b0198b9734a2ed5981215e1727f409f3e1a3
postgres_prod:
  host: 1000d406fa5e407ccc46b7cee2c415819a47b3096575cd35a93b9f3182159195d537
  host_slave: 100054baa0a1c20e3bfa6ce76a1a59ec019ac8529c22cb3fff4b168425bf45e8aa6d
  user: 100093b8bb0ca50fbc11e9f6fcce6a2c2de4435dd9a36329d2db3f79a21901519024
  password: 1000587931de56fd107ac41ff23e869df2621aa082444b3dfb19875cc41dda43a4952401b33cdbfde8a4ac55415b8c935850
  db: 1000a2c5e9641fdbbb7b4a8e92d5cbcc3fd4a0ddcbce064e37340e76d56a212b34e6
  port: 10004d3081cece44474c761cc2ef7f34e5172b4319d21e63d943b986585b8921eb30
params_prod:
  api_secure_key: 1000d95f33b757fb8b1055a20b94ac98235f130d30fe55b83520f24b24a5675305617156885749bda66e08055dbf453222ef
  token: 1000a7b6d2db9b2075f1e0d356f18f9bd877c61755915833e797badf674db9f9c8cffe09e43b07013bbffd2113bce91784c840c5492068134f6da4f7fe7bd0824d9e
  feedback_api_key: 1000ddb44ac5b774e0bd32ed28b245d12ce2f1bc6b57ec26446295d583d53c78c5e4
  mailer_user: 10001cf575b36b03469c753572e02f0ff69b15b547b8496fa13106c8718a431a4638
  mailer_password: 1000d28747e39541ebae57e834a25dd037c40bc6385c0f37357fa584472a365c3351
  notification_token: 100016d08f3cc88c98c644ded5a5a60a47699c9ab6b7ffba5bd68fde9f603247c3d2bce5c1767f81b53c2c8c43f6dd63fc63
  sms_client: 100060d2a5e79ad585d048691264a2e86b21dcd5fe9ccfda703e2a7664e686c2fd45
  sms_password: 100073cf8b23a68f62bf3405bdb3f0fd358f659c27073152cfa45bb535a94e8ef530
  monitoring_email: 1000538b4d13632bb91d349936cc10a2566e1539d5944978e72d72f8c263c39ae3d6
  vps_authinfo: 1000a2814970f56bbe79aa3796cd8c759594af2eaa310586bee19561eba28938a38db337ed309d9f17a17c01b4368d9ff688
  sberbank_api_sberbank_telecom_user: 10003927f5f9faa2bfc05b077bdf6b5fe9f50fbebba9bdf05db7c88ace79795fea69
  sberbank_api_sberbank_telecom_password: 1000801e61fe438e2efdbb5a870146586d70e1cabf3f17ad62637fd2fa969284bf39
  sberbank_api_sberbank_retail_user: 1000eaa65087150ec6040996684fef7609ac8ff887d454fdbeeab1d66cb85877fa53
  sberbank_api_sberbank_retail_password: 10001f523bc1d3d4c27cd5a94482cec17b7b6c3291b543a5913ef8c724eaa4373e84
  sberbank_api_sberbank_service_user: 10009bbb0a2451684ad5b3ffb4297bbca1adc651a75348b149cb373fa88a52f68dcd
  sberbank_api_sberbank_service_password: 10008eb1217afb6db31fda4dfefba8996d6dd5c1c54f8ce50809f8fdb0cd4f4d68c5
  paypal_default_user: 10006d34cfbcb9fec21693c3a9e3066edbdc1990c20de51f6fa3d23b0409f469711c50e5d9653d6b34876e2afb6466d94d93
  paypal_default_password: 100069ff963c39821dc51b6d144a1fd2ffe34a862d44e742f37b9a5122743d4bf48b6a40aea7580e88b60143fabb81252372
  paypal_default_signature: 1000f0853b7b8a3f5cd8131c034e95c08f3e79e555324f16ba6e9a00a385a8a2437ccbee74c4fa12bdc17ebf4267aa0b81a0359a447a4afea3118781fe4d749189419310d604d3d6f033f38f54ee386bf6bc
  paypal_tel2tel_user: 1000a2812c7dd53492a1a27bc2cd3b2db66d60333a5b373c1d9d849ac2d8eabb7918903e1e3e39727e65a8be64e0c33e3530
  paypal_tel2tel_password: 1000965e7ba5f689561703e2ca603e132bb11bc6324b7f5b14840da58e7869da0f448fe8dd0d52c3b0b57c843f33a6b0806e
  paypal_tel2tel_signature: 1000e06716995b03159e4c8f24b555d1e3f7d7662302792d83eab99853913acf9fcb81e979c05be9376bc466b92e767c45abcda484b7e5775a3935e0f0fe37eeaf5bf222c67dad7bf77d6fa038c3e6fa1973
  yandex_kassa_telecom_shop_id: 1000639c15a0550f5c024a5e0829fd3561b3c165d6c934343dffe58e7f5d4f180d7d
  yandex_kassa_telecom_sc_id: 1000c5371dedc738e987337f2cfa156591408f666ad1e0cf510e77fdadfa5d2abd1c
  yandex_kassa_telecom_password: 1000755ed3bd222f371a87fed2ab1ae1a93d0aac45ab2cfcfb46e1ebcd867f2555d296c8951cd1560e9abd29be4caa4eee05
  yandex_kassa_retail_shop_id: 10005ec71300f5b4b4eccaee0414f2ba8905bf8d0f12d7a3537f941d66e81ffacfec
  yandex_kassa_retail_sc_id: 10008072d6b60e2ad53dd37da879a5bd3e13c796d58ba72f36fe664ae79f2ba7af5b
  yandex_kassa_retail_password: 1000a345e06bcf56721659c3b01b655e5488384a2375776ce0ec2e21d18f773eb7f4663bb4bc26960fd5dbb8e2691a132378
  yandex_kassa_service_shop_id: 100015c51ecdc8783e57d749962d296a75df79f4f978d376eb0f22062227e0eecb71
  yandex_kassa_service_sc_id: 1000964ae74ac95fbeb8ca224ad8962600dd72ed5f78162d5d0cd6ee7e33ae5e736e
  yandex_kassa_service_password: 10002468c74b3e293a54f169e68adca6ba6101edb149bfcb635cc40e1e54fc917b82c4ee78f9b741a0f86e2868eb05bb05d0
  rocket_chat_token: 1000d38c8ee98654baf3ed41dbc401de1a2e919a505860736a070b9e63a143a437f82914049ca2243f279e051e8af6b4dece28784fdf891c53585332a3c3909c2bacff24ff9896bb6ef1a3d9ffffed78f993aeb7c21336c46e454d32771726f47250
  nnp_info_service_url: 1000264524fe9cf225446eae42895eb0578d440cf616674b28dbfd62c8288c4467bd70be5c385f7c8607308d4e5dc5d3d4bee85b4a6c2d728026a39189de30d81198
  client_changed_amq_settings_host: 1000ea592c7a96a728b34ee32a7dffa82282aef63e846484faa30cce1e92e4627d54
  client_changed_amq_settings_user: 1000f8f9e60e2fcacc59b8310ca9226e9beb8004733c3c2240a470ff90fe0c51328e
  client_changed_amq_settings_pass: 100042762d5af2fca3e3601fc508e728966e4e5400e14c905e799ba742d4a9e9690d
  tele2_amq_settings_host: 10001a31fb4a2f8c12930030f71880b40bb350e7a928a81d0a29f1d2d38e3c109064dd49aa36d76b39807404773c95b9d524
  tele2_amq_settings_user: 10001aca5d807069f707bded019400791796b8407083088fd034bbfe55578616096f
  tele2_amq_settings_pass: 1000ceadd1b444d42fc3ee021073f1e5380f01213c575bcce1b4c61ef22d42eaba0f
  robocall_auth_token: 10000794570a76d7249e4009a267263155926cc57e437a57bfb98369b06c26df38d6e4d5e5ff8c35334b9b7b970719fc2b553165f1c05c80de31882d89785a798180
node_comet_prod:
  secret_key: 100000f5e57f3822d96df742ab4555082ed3d6f0316a40bfc56caf4b54281537c6f51c797fea72e1ef859ee012436c0cf572
web_hook_prod:
  secret_key: 100063a0649a3bd9e2129c114c1d9eabcba54183a56326ef8ddec0926eaae040fb98f778c68a7a471366e3619013f3230cf695cb1ca1ac35df37b4a862489f8093ad
  token: 1000645c75e2e70bbf750af9038d21b1258e07f4fea733e2cad7dd561d6cbbaf9472810642ecdf7fa6a96c23e22870cc57cb4c2e35f5a711bbaadf128912c765c169
  account_id: 10007dd42d6c6294fd0fae4a4d6638f312e568a304267cf2da9f1f33dd534d37b95f
  vpbx_id: 1000ad39094acea05dd0ab02cb648b6bdf6f3f2f0f6f93341d728c754fb42a8881ad
payments_prod:
  user: 100064d6392a7499fd2fb48e7ff7c18e1676108524debb4c960e5a003b94d45ead61
  password: 10006a3739b493eeacb7e568b612a0d70d34223fc2e184153fc701252ce20722822c
  publishable_key: 100053ced7161d1947ee0dc88a770d2ff1b5c494b935bebe9ff743b723ecd875bb7369e5abfa03fee49f99f69f0324fd3bd12eaee0c46245599511c7708ffffa54d4
  secret_key: 1000b76afc33f4365a8ed9057d4ad19811cde18bed5cec4cc49ad2703b171661d4611fe5d0ef12aa5ffb76574ed851072475ffee316f97688625d5c5121554ad471f
nnp_prod:
  numlex_user: 10004e357a9d2848f0593ee91e6fe92a3a02b1b4f34080aa45aa408be3cd62d15f35
  numlex_pass: 100036131cefcbbdc4251861b55014003cec4f7c2e7709be24b8f9e842204a03e6f6
sbis_tenzor_prod:
  login: 1000a0b53ddb2f45b37d39b7f539e9dcb70e9e5ab0075d9aff5ba86cd7aca7dee928
  password: 10003bf958056672c18bfeb3eae945a02d5e76814b4977563e6b35cc820fdac77867
