mysql_prod:
  host: 10000e21393e29958ca9cd4ec641b10ff211aef2533d292de964379c98e9b3ea9217
  user: 1000b82f3b52484c0926fc59d925593475596b23ea80b5d42bd5b929e8be353dc2f6
  password: 100030e1b592c414c073b0f9708f0b9ef86036254fc9ded91fccc0995b54b160fbd7
  user_read_only: 10004bbdcfed95b603e196c446b896ead8d6bcf23c0121c7e0d68660d2c1a79b4310
  password_read_only: 1000d6ad64b0f9f38bdd5ca09c6ba9798ff7d34f11a20746bcb9810fc66812af64bf
  db: 1000acad409bc476550d89b03681bb328a16e74a575c54039a3039d067b7af86dd6c
  port: 1000471e8e7d73206a284fc5654b183673a4a49d2fdef2478baef1cb982a31248e2e
postgres_prod:
  host: 1000cfeb7a2b876945a561c46892b84dddf471a4acf75481d18aaf2eed4bf8dce306
  host_slave: 10003066b97b74464c1000d4f47e0f62840164fdd9b55ccfd1cb9d3a16352dc85db6
  user: 1000ac847a1e3f80d4a369bb3a1b3e6249bf0aca1a2eac05420f3ea88f3d93fec1ef
  password: 100038511397e864078219a00944011984476971f6bdf6d16c6f4f4465ac4d8e2f5fc4f86a16ecb932d4e29cc03a66d61890c068556067e7356d059af6e907fa020d
  user_read_only: 1000db740651e26a82b775025a4ecda2af2f9a31698fac1f8cd29c720e2b011a318f
  password_read_only: 10003d33cb891e216949aea281cc5c6aa32078e0dc945f264efb44c5e57a0324af8c49cc36247e5ac75dbb3a02cfeaf9cc36
  db: 1000661fd8a2123c270b631daee59ff24856707b44f4d2e9a88bc37c7e898e1a6529
  port: 100008957c5dc85caa0061576e52cd225b8dbc2414169b2781a27279f07af235aba9
params_prod:
  api_secure_key: 10000665566536764106e44f3537a4ca26080ecbcd279dfd8eeed9a993c259bd903069125282118f3a3b139d1cbbc5865d46
  token: 1000838c38d75a6d7550ac84000f71ea64d1e96cc14317b319dc56d9070c61109f68373bbf06a98d420208be084ef0f31646a1530cb0f5788a3cc311b359ce7b74bf
  feedback_api_key: 1000a8e43a2d7cf72a23a53e4cf667af3604945f9bbed549852ab0a4dc3b4c5c41ab
  mailer_user: 1000437624f4a6a2778942b5f773300e53ea7cd6b38ba67eba72370bca3a674f66a7
  mailer_password: 10006336aec28b8be61d901a5d2266aaeb30df9385ff80e53e9e8748929e08625212
  notification_token: 1000b6f8a56895818c100350459231ec0713fd52216c1b3792bb40d5e2728a09c5c8a65a4c0131f9b05a9ed1864df9e2cedb
  sms_client: 10009bfab45d3e1df4f0c6f9bd9934872179d492ac05e6127c0416293a5be9e9ce92
  sms_password: 10003a96e221b580565ca223152cf7ce553ad6396092d2ffedebfb58c9f62c43a1a9
  monitoring_email: 10009ddbe75ea6041f6d1fba1d5097b700dfdfaa9b7759571925c66722761f427558
  vps_authinfo: 1000c67f93e53baeada6641c4732b239a279866ba9dbbfd00388fbd77bbe6134c23d79e4b5f631e7bc173eb183ad2f69c16b
  sberbank_api_sberbank_telecom_user: 1000be065bc39b76f96f70a06933a9b29c2f05b53b8c7979f7e249e9c3041c858da6
  sberbank_api_sberbank_telecom_password: 100004396c7aeef24e57a78286b51b80c1166d0c65876c71f2f2fe75f266c4ae5e9f
  sberbank_api_sberbank_retail_user: 10009d1b999c21313fd531be5349ac29602422e0e60b7d7165d7fe6511af3cb0194e
  sberbank_api_sberbank_retail_password: 100031a3109750cf05a7d8581f47652fee7b84dcec4b423635dd455d65988cd0bec7
  sberbank_api_sberbank_service_user: 10004f5d163f4ddf30090a7f84ee7e68b7e8953ae54cb2a5004e86a8561e75be5023
  sberbank_api_sberbank_service_password: 1000514058f68fe1455fa7707cd12d1f50239f61e2e8e9651c9c5d34b899ebb57425
  paypal_default_user: 10009c34f31f5a028939ededef8af0b0b516482b59229cad5d415fc16f2daa4c5126d77bd90170e408f6bffc53c8e00c1b3b
  paypal_default_password: 1000346a9947a93bf7cd7f00229b2abeb65db6e91ba1e498483a1b9779849a3df72a5405df186715ab5d83888729bacad848
  paypal_default_signature: 100025b7bb928a71bf1f3deeef0dda9bd861be9ea6340e0dee1f730c22d890a6f22e88b6e47b024bfeeb0bf5256207e64388c8c686603f0cfb72f61652daf74fbd9b33cf4f9d357e7f1d494e0e8d935f9d07
  paypal_tel2tel_user: 10009971d9a7258c53a9474ec3335f8bcf700d151a63595a7a52e6daa97d013ada0a74839c45246e8d96378b2806d1036420
  paypal_tel2tel_password: 1000d9a3959fe686bf400ef66af55c55185ff81d51626abc225a26e7f99acb0c1577c0c70f16160bbe4fb613d86ca7981d47
  paypal_tel2tel_signature: 10001d07d966ef38763bf3c695802603b38a1aa9e3da37c2437983f407cfc41e477bcc2fcffa2188380b40bd58a2c5bf199d3ec56a17f144c1b25012d869d0897dc2cb8fe132165486bc1e78bedfded7b520
  yandex_kassa_telecom_shop_id: 1000eb8c73a81364d70cda3a3ee2f2a35c8ba20b6e26e6820c3eab0e6ee79b786396
  yandex_kassa_telecom_sc_id: 10003f266a1f51bf63c97654b5e4287c654a548b5410416fca09b8575f0ed01f3b72
  yandex_kassa_telecom_password: 10008b18c8b2cff50f99e81699d0e0b03f26427d634cac54d55316ae932bfb12988acd3ba283ef725386f6152df2725a6096
  yandex_kassa_retail_shop_id: 100084c2a493836d12ab43fdd9bae70c66b48601d54fda7ee3e439632d6ea13ae071
  yandex_kassa_retail_sc_id: 1000ba5502eb3ccd2077e7061db75dd962d0eaa883d98f47c8d806cbc9ffccc54e47
  yandex_kassa_retail_password: 10007ae397ae3c1f8c3bafc4e7cbdd50f8f4a32734f6ed569123cc206a9c95474ec20a57552eeb5ef4c32cacfe5fe6060626
  yandex_kassa_service_shop_id: 1000efc0b9abbeb55a9198a98a56f311a5de38005440538cdeb6be5e72d4b675c5ed
  yandex_kassa_service_sc_id: 10006b9deabd8cfbe6b862050bb149081d89ada0736fb35549fd227b654bdbca2352
  yandex_kassa_service_password: 10009fadfc4dc313a276a0b016303174c520eee01ff0dcb0b1533aa479fed352125af519f9c305f54f84f5b3c006b420b5c9
  rocket_chat_token: 100014b96e53d6dbcfccda8c813b79199d5be696417370fa5af923d788008f09ca59e16d8dcfac5529a254f19436ec38df5c7d80aace3ba0ba9fcebe19fdd3d3d47d7f8ec12f71888702c32aaf9bb02f5d2bfeaee1be236e06cc12a9ffcb1a7e784a
  nnp_info_service_url: 10006241ddab39ace51030ae329f5589010fc4e5808182ccc488385a0fd87ee057173eaedaad4ce047ec6a1031aaf032ceddaf48e9e342a2f45d1172a9eabf4e3d4a
  client_changed_amq_settings_host: 1000dc33de8f3d5816ba66fafa8d1b2b612b3858bfe090f2dff0e8758d99e3947e6e
  client_changed_amq_settings_user: 10004e2a0c9e76530406e58ab2a94cd500b8481b3612cd536c11cff55d905b701727
  client_changed_amq_settings_pass: 10006678e6c78c761a5e45c6df69d57abcb1291a608e49b7965b7471bebc58de58a9
  tele2_amq_settings_host: 100058de58d837285d074cfc86183bf4d8b403ab42fef91d78d6a04253dca87ec4e88d8487ef47ba472db56cc494db727fd4
  tele2_amq_settings_user: 1000e337602291ff533d245dcc43f20791a53f47d4552d6c79f32b6f0b2f25c5395e
  tele2_amq_settings_pass: 1000bc85124fe55e4a82b67de5da23f0f3aa78fadf49a3ddde9c33ce56baa8d46705
  robocall_auth_token: 1000ed74f87a17acebfefd14b348debd82def7d25c9894a8aa67cdab240af021536ed94d44c3b75d96b98d3f4d6ee6b5d2214ce38568e79b1d10046b99922baf0bd7
node_comet_prod:
  secret_key: 1000cd8d328808db4214a109b7f6fda3a4bc517ca27d0732e32571acfca7ed17ea27548f1f0e6b63e56a8f304e7799241630
web_hook_prod:
  secret_key: 1000b82020137fb7bd7232fe9f63ed49ca14adf23df66d78e925d119b0997b4f489ec2225c6fdc5cd85c2cd281eb63c1ac5f37cb28f7b4479f6b528b8f6e0bd9fc7a
  token: 10004374951e739e6f607e0fb3f000955265fc03b2c959ec1299bfe0146b72359536e28fc3797fab9677d4c6b02140a1bf218d71ccd0776b294c4dce7f5fb346f302
  account_id: 1000ebabd6b5f31ed6d052f4bea09ea184618a9c8b3f5dab31885938d10d42b7ec4e
  vpbx_id: 1000e2b6a577cdd8833686abdfaa412b97f377dec6fdf67a4978e1a9448546439376
payments_prod:
  user: 1000ae1d8b573c44f72a0cecb2555b99645dc96a04d9642aced8b99bac7846b3209e
  password: 10006bff0bb7620f2f482bd9f1aa34e5903a1d8663320180b14385c082ba5dc7ed0c
  publishable_key: 10004df332f4b355ef14fa7689ce1430283296f6813cad0946e2436ba9e85b2cc379ef87724244884c0517582faf27f6c52691e8928b6787c36cdb5ab7c3a81da451
  secret_key: 1000b6d16d4ff7e76e815b3e87b8c1326b74995a2ca6d3b48ddbbb50226686a34a6d7e270380dea42767e7d2ed8c702f2a27eb06dc6a907641722b52c960153765f9
nnp_prod:
  numlex_user: 100093a05fb82a0226baa0471c443a1a318314ee1171b61d22ba9cb76dd642a25e7f
  numlex_pass: 100002c8060551a06f1d6badb4cffa702ffce4c2cd2335d777658e7b5ecd09a79b4a
sim_prod:
  authorization: 10004fc862fdca6749bcd133e1da184616de5d985c5078485ba797d86d1fa714b06dbd4c4a665b6c691afcd218395b2663c1f6645b32334c87ef3334376b1fd54f48
  transfer_msisdn: 100005c71b64fe79da1ca714a8ff7ad59ae10c3c63696d8361a9bd48e1085eb1733f
notifier_prod:
  uri: 1000de87dbeba7579369f4e2dc198cd4fc9dca4dbde269317b520d5b7632f520660e4442ec8b676a9a99fb511badd00ea778
  user: 10003a60b99fa25bd0280c008e1bab2ac06c01589cdc5090f8577eb70e9e7393facc
  passwd: 1000e183a6e4751a49fa47b2bdca92eab912ebf5dfb04462ef15c841018c03b878b9
atol_prod:
  call_back_url: 1000f39bce1cad06d180da8e7e66aed9ce63c613f0e8afb69dae85ddd18a74313f1cbfc5bb249370478396fabccf08776317
  access:
    mcn_telecom:
      password: 100076523f74e8b5e3a3b4039353c58da9fb8958c0d2fb3a7a840ea4dcbb39fbbdae
      login: 1000831396cf3e7e2c461412357298f9c5087a9d2bafc054ece797b0817afd76a4aa
      group_code: 100094a2cb3955e703658eca5697dc79494ff49b898adbcceba00f33b1855faa1cfa
      inn: 1000e6e935577585e26ee55eff9539be46f72d186599d117960accae8c1447eb8a4c
    mcn_telecom_retail:
      password: 1000c42d8aea3a2f794cc5c7def27dc0fe6ffc063ed184af94d0b38756a57152b37c
      login: 1000f4cd2aa76a70a5fed85c5c04f1b300840df6818224891ba09ca33bb2b9a930cc
      group_code: 10001a6cb2ae80fc8e68404d99215a46778222bedcdb853ac19e9faf60b2ecd60854
      inn: 1000bb1c90ac7ae0bc2355de2ad67681b9cc620bd355e6b9a95e25c751706deb25d3
    mcn_telecom_service:
      password: 1000aebd7d070a4380fd85d443f58dde69fdb373befd264ff797e37e46e0f8223594
      login: 1000d522db155d5599a875a77bc3adfcd787b1ac2589957b8458b6dc688972cc9412
      group_code: 1000da33214ba4b73b4c157e979e79e16397ef0a26151fb30a85570c9ef4dc79665d
      inn: 10001999d304ec8d9743633a8f78e3ad315abf49aeaf4cdcf6ee346fe4a99fcffc33
  buy_or_sell:
    payment_address: 100014c35a2bb5e03470ce938d3798bca9b02714910c68e19359cce04780fd03f1a6
    sno: 10009177c0e89fcc9c8c6786e3275f34eb260a9f44a0f5303a8c986789a753f73a4564438a0b2d982b90b84843bb56f69e78
    item_name: 100086c9aa7070c3d64adaa2060acb49cbd2dbe7bc573897a4f440ca39fbdb94d5e0a5a49b5323568bbbf09ec3fa436690b2
    tax: 1000a744658ed26d5ab7b1b9388fac19b032fa2a918fe70c2ea120c4f86d7fee1c23
mchs_prod:
  api_key: 1000f7a18d21f35b48e4211cbf9794b079942ed55013c6e1d86ac23bde72683ad9c2d5d9938621f73454e224038f8c8e7b2ce6ab23d296f85273241cae4683d18e76
async_prod:
  host: 1000eb6e4c7303ccbd885196df3ea076720990272b4eebb3bf3631f8fde6da334149
  user: 100016297f35c2ef1187c173efb40f204af95c38204c362c68d9c6a2eeece936e2bb
  pass: 10005654b184d1ebff8f17dd2eb6a9902a124465db320995ee87df4d550700c53736
sbis_tenzor_prod:
  login: 1000c376e34d5cfacb82f9f9f2a1ba9130aabecacdbe48f6f828fa109546085d292a
  password: 1000f0166af7040c7b922662010a3bd5b75c5772fa333862201c54544ffb0f4bd948
