mysql_prod:
  host: 10006b06e74cdf3231a83101dd46e340eec76b389a0a22b6084bc3630c89bf1f73a4
  user: 10003d150846056f452a9b943fb8555a491578b1b21185cd7e9edd3b974c4d4b6c70
  password: 1000f0dcc97cba235fda795cda842bdf5da66a69a03b06904ad7ec4768a17b1bb911
  user_read_only: 10000c60935157957c244ff6af944aa6ffb795d8c04ac9d6709b5d8fb5fd25a1c9eb
  password_read_only: 1000d7eb6b5bf859b240da5c619cdd471fd71de82b054447bbfb7bd9ba1f7c8612d5
  db: 1000a12abf914e0ff8450cee706bba6ef0e007768bff7d6ad70c91bc29f5405438e2
  port: 1000788f9aed385bc257b0fb0c58cb4b62b093cbd8d3d6aa367e71a44f1b02be5762
postgres_prod:
  host: 1000fc78c9bfb72880528453a70b7061a223927f657c1f5214ee963c513e162563f5
  host_slave: 1000c8ba4db5c3cf809e5f51fafcee1a05f99a2827b7144e0231a17bafa5465b90ac
  host_statistics: 1000145159fb951e8c6a2a1b2da7d19ce337107bd2ef56f4e285a58f6195e7e328bf61e6e4688cb1dd5921782378b93d2d81
  host_legs: 10000c892c9c445542ffee92b8f392a81fa5d58e541cbad24421cbf198304c21118a7ceeb877e3daccabe286fb852b908585
  user: 100088c83c98349f3d3e4559b8f462e0f6dd16b5275659fb5cb3f6242d5c1c630695
  password: 10001105a94b39f1c6d9bd977ab92fb1e2795535e4b831297de3a38ea710c672e6e847b5d820604f5d56370dafa3c2df057608a694ebccf40b975071ca268880e270
  user_legs: 1000d98776ecbf374575acd9debdae2443a9e230b6db7c7d1cea0d3e39b03615e0e6
  password_legs: 10000acc9df96a83775404b148372334666a0da865c54fad13c1cc605cf7116a84b9
  user_read_only: 10005c1ccd1c8b54520f75f3d45acd2b6a7436654f7f88f9341b649c16ccbbd25db9
  password_read_only: 1000dd436ea4faab276c167f14f170b2bb729467b09ce050c10a5ac546258a3a42312e6d102f4547c67e308357eb1be2c5a7
  db: 1000a4391cccab45aa5136ae3f70008504e9a9af3752a6cae379083d3480209a174a
  port: 1000278e83210352a5281ed2adb18367ec569dc93b77657103b8d59cd56507bbb37d
params_prod:
  api_secure_key: 100097188c4c23cfa4e46ca0edcd7a4fbd723a331ffe7e77b94a136b152b392176fbdf2b537d3729a1dd51e7ae4d44702440
  token: 1000b0c8f27b94dae0a1c48ead648c8ac5efcdcd212b0eac439b67da9fdf03130fc6a758901c442e35e73bf8c2b400f139b5e11dc2a8bb6c28158d33b184ec87cfa8
  feedback_api_key: 10007796bb72744ad200660a359944d2c4942d333da2390b8b9d52f1d5d3a86d6890
  mailer_user: 100031127573bbf13e95704f360e1fca2dee2e7a321975686c8b88061a680c63fff8
  mailer_password: 1000a07e0c37eb8c45221b92e76521512f7a41391153dfdd821b5fa81b52a20f0e2d
  notification_token: 10002391316235953792392854f576b6e99ad080965b166a1b899ed527d65acfb732a53a65a31812bcbcdc34feb0cffeec85
  sms_client: 10005436bc2af6de9745ae434a0a3418892e0fb62847555d33f075a031859ddb2242
  sms_password: 1000f7c4d38769060eae29f53c2f45bf45ddd42f09edf538ecd7ba528c9eda111e7a
  monitoring_email: 1000769b2d7308118a7d0da955a6b452782d9fd8320ac8c8f3b2d0a7d0be8ab37815
  vps_authinfo: 100044eca066905c4e8d568ab27e2619b5efd0886dfaa0f8cb8635a4ccd18b19224843a69d2f496e1f4d4b56da98a2435bd9
  sberbank_api_sberbank_telecom_user: 100016ad75d80bfe749356927331610992ae748316612777deeee0c696572f9bac0e
  sberbank_api_sberbank_telecom_password: 1000534844c8c912af4a5c791ef53a1d3b3b5765af6d989be472d018854411cd88cb
  sberbank_api_sberbank_retail_user: 100055bf6855a93bb3c34d3c061a4f936e1fe4543aa07c19906b31ee86247603246e
  sberbank_api_sberbank_retail_password: 1000a2b96f3206a04b03f18ad978ac8624573776d7f3b39d06018d26f32e74886542
  sberbank_api_sberbank_service_user: 10003b0b3adb127cd335c718754179d707d50a4427e158ebe48c5bdb5aae641350a4
  sberbank_api_sberbank_service_password: 10008893e1fa3734ee606b48a7957ccb8a0fb7c74a0f24213fdb50ebb1ba151c35f1
  paypal_default_user: 1000d0724c4298fae69c6212057b7fa699a76d53b9276a10c0fb076c3c4db0abe159ba615df04f0d02862cbe8e8877031f5c
  paypal_default_password: 1000823665a4da538a4305fa4bcea2dc28433c60ef171ab2f6542c858731cf97da93c9dd3a72b5159f1f5a8bab56c9c30568
  paypal_default_signature: 1000dad6337bb182580ca023311e49ba391eccd7d00281425f2cb2ba8f5cc006e92e1fa2d8d16338e484b320a353dbf568401982f519be1f818eb7c94604e9a67bfcdd7a1a128d1d1e2c68a78ccd39e9db39
  paypal_tel2tel_user: 100037288d9d21412b84655767df2397d77409b40c2b8e1c97f935bb05c01ba2fadd796e583540c86861aec289b7140c024a
  paypal_tel2tel_password: 1000698d0a48bf8805e0c3b2d6d65fe797f3401405500ce29e5a8149bbc350d2415a3d8875e1c71ab90e6bbee8adf8e9912f
  paypal_tel2tel_signature: 100067c45684c7c332e278101752d3ec73dbf4b116b7180bd45d91d8003424299ea160f38de87e1c83d2a1fbe81f55d78da9290e017159a66f4b1d37db94e7154ed7610eaaf1736d65d0bf88ebfe71bbaf18
  yandex_kassa_telecom_shop_id: 10007b31f66132bdcfc1be7f2c4eed7fcd163ce89000fe06c20108d2b381a3426bc5
  yandex_kassa_telecom_sc_id: 10002feae087630ab81a5efbe381c12b5edf782323f0eddcf0a0a1d34a32e7a8cbe6
  yandex_kassa_telecom_password: 10004a7bda1cc7e75d25cd0b3e7c345c0632b3f11da54ab77fbb59d39000de7e294e4ae0915e9adb41a09e4b272d0e7b632a
  yandex_kassa_retail_shop_id: 1000f33130b88884bfdbe8ceb72afa56d1407c79ecff02cc731c6a561736bc36b03a
  yandex_kassa_retail_sc_id: 1000f923ac3e80b6ea4ddf83a159ec288c2fd24e227cf6ee663bd4a58cdc4f082a44
  yandex_kassa_retail_password: 10002aa629f6248ac42000c3f5edab4a2f5e8694f7007fbfb65ca5ec9d1669d9ce969dd0c6d105a3ccdcfe48314e77bba67a
  yandex_kassa_service_shop_id: 100059df24fd1eb26869c95dd775017bd300926601d881df18990a42530918c86a0b
  yandex_kassa_service_sc_id: 10002015200e969f3dc7ededada5313e5662d349e00fa5cb292a7983c37b712b700e
  yandex_kassa_service_password: 100074fd78b2c60c36cec68b438e4d34d02f7786b0d4c29b800b4d8c0dbe0b00c98386a0085e92a9968fcc4431ebb3549ebb
  rocket_chat_token: 1000806df928f46c0b65f58c840cf4a2c27953fe57d13e960c90d03e7b0bf9728478773206439793cb67625adf9d95458aadc0353f5d800a5c0b73cf12415efbbc51c13fa23044f1e0e69bf24bb1fd843fbdc68b260f335de60c25346c491ad770fa
  nnp_info_service_url: 1000dd707def81911b6f1db76f07aa0630e97d4b236ff146436f2d4a2c79515bb5a44892e572b18d0ad46a75bf7bff3797c1977154eaf25229104228f478361517a9
  biller_api_url: 1000cc8d60cbdae3ee0ffae80fe4ba2343e1648d5d846c2165bf01a07725c19babe383d4bffba09edaae7732686f4c752777a6ca57d610e177d7058016ac45400ad7
  client_changed_amq_settings_host: 10001ae3cb47ec81d36295ddfcf75bf2f7b5f2ec6fde7d2dd119ea3dabc344f7f66b
  client_changed_amq_settings_user: 1000bd8323c596bc8b7d18ec1658cabc831083966f2582f34dbafe24989e1612597f
  client_changed_amq_settings_pass: 1000fbc7330a50358d0409b486de46b0c2ae22583167d051a86e80c3765351f9c135
  tele2_amq_settings_host: 100004bee824492da74766fefa35641da2e39d56d98461b1a65363ac15dabb5b6d82b67cf13a1717723866c594315a66d8ff
  tele2_amq_settings_user: 100046c3a50d9e04ea74c77a72bb16faadc3914379d6c3144b7ad4cd86e78822779e
  tele2_amq_settings_pass: 1000a03d06bf7510dca5d592c375ad839cc00e485021c23c34cbef78f7ea28ad5b87
  robocall_auth_token: 10003b552c606729bde5bb9c6158b15e1805a0abc595bf49fef3ac3f8dcfeb53c8a999596a09a03b6ea719d4240fbb9821dc98a25440651f61be7bdab876f17ef153
params_local:
  db_voip_regions_r_calls_user: 10000c6d6e3f0427cfe82c34716ac15a8ddab712f6b40123316d78181220941a6fad
  db_voip_regions_r_calls_pass: 1000298668c016b7045ce7bf27282e58102580fa3436ca302a96290c8be1cbf86afa65d38db14d89b14c42b79645e2c947c8ea2dbea891becf232f1c574ab15ca3d0
  db_voip_moscow_r_calls_99_user: 10004dbb4cafbfccc4171308ddaf7f855f594e1812f8bde1dd9b3b284f87f789bcf1
  db_voip_moscow_r_calls_99_pass: 100081080334c11e5a0d5c32633844225d14a147e90c8a78655ea841362a8fae4ed682dbd50b8f856d8bf4b209c7d460acc7
  db_welltime_ext_sql_user: 1000162cac037d90c06bc8f6a4113b9ac97004de46edfe64d22dd9ccf112e50b7494
  db_welltime_ext_sql_pass: 100029f7a7f32ae908e5a0ed019c716a164ba86a4185755fa64cc0775662be95ab0a
  sync_with_lk_mongo_user: 10004943e6a0eb611798903122760912711517ea777b6d8c859c84a3b4079817fde4
  sync_with_lk_mongo_pass: 100033e032a320e84b8c93d5fa2373ac1e657360748702fb917b3c541ee8afc5f3d1
  sync1c_ut_login: 1000b1018d99a149a09dbcd6561542571ca7d81f7e435947ddfd54cde2ad504721e9
  sync1c_ut_password: 1000fb4782692c762e089654f5fd9050c9c784e7b615e60048819cb371267bc2b00de5b9ac4fc093be795aed09961e928d32
  sync1c_stat_token: 1000c3349463cdab5af9236a9408f1f03224246f0e45a23d84f5ca44ebd70cb3362103f269ced8ad03e093a0523923ac8c8be5b73ed682ea692eeb784db65c36a3e4fb6feb8abb713bdd4edbf928fb47f97836ceedbe08e7d5f0aa09171524eb1d4d5a5a56676863972569becd94f7348875ba3c141dd5fb0468d46c01f5bd19567c6bb702c329c6b266cea27325ef025aad40bd6209e117135ce39a231a38f3cd52
  admin_email: 10009e283377d50833540a6d79ec88947360135e5efd61c5bbdf3dd15bc50a145873dc907d5237b41f8121fab628b0414387
  admin_phone: 1000676a7cb8671b00dbf5df0a4a878192cebc2e7bb5a6cac8d7d9b9d99c6205bb1d
  monitoring_email: 100002b53fb7b901306c8a75fe763ea0bc447dc364d5e2c8bf858a596cc913f41d97b7018e1c041f87dc890f7d5474ccfb0c
node_comet_prod:
  secret_key: 1000ed143f564b1823312d1ec56e093ad45528b3eba4c8eafbd2f8562be47c0c348b1bcbe02da9e4dd2277a0bf041a878d05
node_nnp_ported_prod:
  connection_string: 1000433f65e6ca203bf478c9bb425d2140f0ed4b35ff09977dc31513f2e26d4311d204b0e76517c5b5a9cb7f668b6dc71c33db49a9a10d758a29bee0952c69ad782ab62866bb379159add890fb46b8718039
  get_url: 1000db581fe7bf137ebcc2f223fa2b8544e408b507748056f90104f861883f7c2f777eb49db23fed0c18f1b4e5eb8fcc025342066375b74935eedea199a4a1ddd6d3e862d767e3e77c1bc35267f68ceb2fcbe1d930983fbd42de238d23866c0cd3c0
web_hook_prod:
  secret_key: 1000b726317da8749864695de2016795f1f425471308aca85261dfa2678ec72846b40af9f04db8ab833d3a1fcdb4f5113c6753bcd96e7e3e6de7827757aeada333aa
  token: 10004c841e24cdadade4479a499c05791da548f1e01e66e89eaca625b9eda572020cafd9b34744e5edcbac32a95d2f24befe51d9ed32ff7dbf4cda98d3e4c0afc273
  account_id: 10009a45c2ea5dd662cbcfc89fbbcb85ac3e58df8a4daa9e88ad2d50a5235e00623f
  vpbx_id: 1000846182f1682c766936dc4b32ec09a6af4e6658f905745948245b7f863f889e6c
payments_prod:
  user: 10004f456cf2e31b181bf40f2ab58b6ad43f7e4e3f14ed4e66e469cfd76f8139e4bf
  password: 1000782bd10cfd2122b0587a866eadf9f172f75b4b34778c6cb6e5de7f3a4700d4d4
  publishable_key: 1000be2ef745f55388b3ef5f09ea4e29255770c095f66ca32a252e91481dabca98b14e474fa093e69c3ebfcbe8ea0a69fe749593e5b4c7d33963c2ffbd5e7120e6ae
  secret_key: 100017bf8d38d0da21a3b187b7d53c1141c59cc9e9b733418e9889ac88e90e3bd6484e8cbcc5baa682b292bf0120fb37f065e2a134b416988fa8d620df4e799fa577
nnp_prod:
  numlex_user: 1000376f9a329ac38035e473a119e8b839b0608f07df22893208e86c983b0cb0d6f9
  numlex_pass: 1000dbf79413a7d5ccec95a368d66e8a3dbdc95bcaf5d5e08c01435d9ed528a40a71
sim_prod:
  authorization: 1000b1acd4691ff1961180be37ee2b796bf1611abb687236eb55ac38e1f415244961a16fbd501b12bd34066fa3dac476e11c91699b3adee972432fb195031d8fd9e3
  transfer_msisdn: 100025f08f3dde0a0d67d4b10c783325a62329a413cffb27fb3c6e91fc24339f6a1a
notifier_prod:
  uri: 100021c73db4f8ca9f94364553e70bf57e0af5d878549154947a6237fa43547d28b5be365cccd012f9097fa2fc8abf36c6bd
  user: 1000f19fa4cb6e42bf8c6fcd7373f2bf8199b70b8ed6e70e5110ed98394ff1153e0f
  passwd: 100029d23e9ae033f1f8299cef2b4df7f0bbfb673cab7bcc1a37bc0e58f26c5967d7
atol_prod:
  call_back_url: 100035a5d25eb61be94a7e9ef06cf4c293ed04c56a5726dce6ab6ae4856faa508404a6ec3b3c3345eb58e5bafc993d07e2a6
  access:
    mcn_telecom:
      password: 1000cb1da09bbfe7dbeeb2340e31d0c1c07971683d8a81368b8d24a2f17e418a8e84
      login: 1000b85de99fe35979c54d347e8d468e7e6242f1cdff9f7b163f9d78c65730548380
      group_code: 100074da631e3cc5d5cf266ec705df2e1475ae900a7514566d6036581f0ef181e84e
      inn: 100008c20cb7ba4745e2a660594e5560d7eedfbc248e255156e4b1e2d659bcfc7ded
    mcn_telecom_retail:
      password: 100024c35b3c826ad9bf318f0a25876de8df4a2f9dd437fe6cd74ad0d67f91f5f99c
      login: 10003ce60a4ccfc16e1b002ba78032e2b5b978abf199ba85851fa2d358c6f43a7b2c
      group_code: 10006d2eabe2acba543c5855a5455d0ced68252379114d3f5635a985c766771b4bcd
      inn: 1000b9ea325ec10606e1596343e47bfca4b48aa4a21fa7bba5c25711bd7de81440a5
    mcn_telecom_service:
      password: 100081ff18781480fdb524a56c996f13997828036fc295f1136da4e80b1aecb96fa4
      login: 1000702d1c3a8f7ba2357c776aca703dd3e5fb25ae037b92d9505b258ed3a4507b1f
      group_code: 1000b8783145491486248bfb38773028b21a4199f9c599dfa01afe636328876c4b6f
      inn: 1000706572d08167d7e2d0ac99e4a677d6d6432761516a9b3948f197d8206686143d
  buy_or_sell:
    payment_address: 10000ac9f4b52a344b6bbe23f6f572dfe7545779db9b834124a34da3e15f29f7bca3
    sno: 10009969aabd239f6400b169256eca7fa1a3c7a8ad725c99b090d2b3836971da5e8d6b612b03139124f00c6e15e44dd18e54
    item_name: 1000f0bbba8ea72f7e753f89f5c46c10a39c21c687f699e40c0425cf5dd4b453a199243a2ff170d7722ecece775cb4e1e449
    tax: 1000205753751e2cd9514c62155147d80b626c34aa07b3152f23652c05d4495a35d8
mchs_prod:
  api_key: 100075d976e6069ca94c22f4d4afa83c2cbed8f4173f7a00a98c0c1ec7c1f26eec1946cfed70c2c14d149cebc675308abea48f9b7793a649fc1e330095c30548cd06
async_prod:
  host: 10004cf5513f708450bbd535731c41f43b3ed8d8ec26271e9e13d9a58309bb2a8d48
  user: 1000416e2beea13762bf2fe33332751f4477b506b7c74464151c5a58d7bfc42eee3b
  pass: 100057ad3984810838ea116c47c7cba91236bceb5b9ae64a8c101387093d9f5ab4f2
sbis_tenzor_prod:
  login: 100007600da1720f2fe1f5697a9a4c426ae71d699ac9fcb2b838b83e74f3b8264df8
  password: 10003b8e5c1ab03d8b531a460481090717913a8d137337bdc03ff5ea583916890c49
