mysql_prod:
  host: 10000a6aae5221e6cc6aef536d6dd04a718f94454958bd24827c1d11369ac381b468
  user: 10002d3e81801a1f1ce689b26e478f03fd1057ccf7cc55c9deac958904abc5bf38c1
  password: 1000ccc5c8111544e91c95a1d720c393d8641c2b80c5e49828cc2880a60f96faf12e
  db: 10001baf4bf6642cdabc945321d1ade1cda83d2b45d57d6cf1bcb2252521b4b4c6b8
  port: 1000a550b6c211cbc993c3e7615fa0b24495dab686db64a4556d8e9cee5668a6f7bf
postgres_prod:
  host: 100016c40a450dc4bd3355d3d6437040a35c3ab4ef634feec200c8c91c03653d1ce5
  host_slave: 1000d0520c5d8726685a4b01f21a3578801470e97225cbcdda082c636250fa15587d
  user: 1000d483eda513f26cd0edbef919f8ef377f5ede7b36fae905ecb802b64c37131f14
  password: 100074b6d9d6fbf2627371e0dc6e98a0c7364aed2e8fc74dfc2d54b2ef6e98ce145e2a7b534d24e7e1cc37ed63475b33b726
  db: 1000904901ae7f03f1aca3e56c5440096c8c3cd0b4804827f8c2d1c28b090b41a500
  port: 100068b945da82b700f2df08904f2d20f26621e9c96d567dc16bbc6131ce5afb6688
params_prod:
  api_secure_key: 10000522cf593915d1533f8642169975f719dfdb3a02c1201fe179548708bb30c343fe291b9853179c69666e472176d6c67c
  token: 1000bd2949b8e162c29fda0cb2573e868d527403f2efee759ad226d69a5d0a6f8bdbd004ff94eaace3e565315a685c0208e54531d2e3efef0fab23773e65e88c5720
  feedback_api_key: 10003b58fd2674dc6ddf5ebc24909c636aa8b0cc5e393d1cef1d56d4e3fa51dde261
  mailer_user: 10006f74c63d2360a722c58475b86d3543146d5e5de529bc240acc820b9c2c2fdb5e
  mailer_password: 1000cc8a50bd90a1c1384a95fdd1e31b4d30371d49bb434540a42cf2a439b957c469
  notification_token: 1000acc398eec88312fe95aaeb210f6ed1919d648831e7cbbf5777a6a1e631fb8fbb0e4d76b945942275a620ff7052390b48
  sms_client: 1000cfb400cb3106c919a00f93c78650b75a35b486af7d59c26ed21d6bf67ddda4b1
  sms_password: 10008920df11be2b04be24fc10f3dd0584762ce00a596863222211675d6097fd27a1
  monitoring_email: 100027feb303dc85b3acd41d8b90c3f3e37ec5230951aabcf046bc124fe01953f256
  vps_authinfo: 100062ec2f545e029f0b23cbbc4c6a41ff93388280bbdeda84bd674307e400100c420144ba211e1eb5e919a2b0bd4bcc6e05
  sberbank_api_sberbank_telecom_user: 100022e8aa971bcce2b28693375adeb212926e0ab1c1813e6ba9af00d3eff891a9ca
  sberbank_api_sberbank_telecom_password: 1000111de4ba36b4a85d57e7bfb4cdd0581c7ce0fd9696d24df27fd7c68a08bea8fe
  sberbank_api_sberbank_retail_user: 1000668392ec192fa9f7a5f9b42585a783b71ce0059b23b22a13c145911bde874570
  sberbank_api_sberbank_retail_password: 1000fd09fe845b2de18996b4f9c62233573a9ddd847ab8fdf1f7f9bb3d89360aeb38
  sberbank_api_sberbank_service_user: 1000d45cd36a3dd48e76c1e6ea48c15ed98cb51ce7010df5a96fde6c0288632211a7
  sberbank_api_sberbank_service_password: 1000021a228bbe71cfca5856487a20075bd2fa9e5cb789f13015930c74b9a728bb1d
  paypal_default_user: 100010de87646cf3e97158e557a45436d97cf8c889a517fc46c6763852b2ff1e56690b091eb09ad2df2dcba7baba0398c1c7
  paypal_default_password: 1000ebdd58c594e766ef8a82886de00c07021458e384e3090ad5384207482c84bb18f8e99ae8d6c7051e065600c8cad1bd0a
  paypal_default_signature: 10001cd660c9786edac8f5f87571fb0538933a48de41215be84f450623b3bb90674955534bb22e8ee4657ef710051433e6fb0c88c89d604ebf16f18727c64307e3faf911f1861ffd4f8fd89dacf45a9862a7
  paypal_tel2tel_user: 10004d57dfac588b1c32f43a7e5a222ea9152288ef403a3ca105b8159b3777566c34e8b3e8ab01e7a1ba5e68e5ddf77692d0
  paypal_tel2tel_password: 1000056dcb9caee6a338b8137559c30fad9bd4babc303e16bdb2449d1e4d01048788c077a9b39146a969c3c531731f66e2f4
  paypal_tel2tel_signature: 1000164adb4224ea0b2e9c2b2358bfb7150ff909fa82ae5f9a70eee5383091094af682021b0c34ce12e3b7f39752770545b8ac45cf4d8362b3eff801d666cc8cd803ad4eab246cb14314eb8103ce309d3933
  yandex_kassa_telecom_shop_id: 1000546d1c373169f4102d7c5e0faa344c4d1b971dc95e53029a22970bbd4ca89d33
  yandex_kassa_telecom_sc_id: 1000bd1d1e68b6ed77fc3a6c019f142480118d2dcd8961fe688235e1635bdd23d57b
  yandex_kassa_telecom_password: 10001fee08ec514d56a2ba30c8df8976bf2d034bbaa4fe333563f9b9fa51a05e5e842c9565488af9e647e44cc468cdda215a
  yandex_kassa_retail_shop_id: 10002cd8a0439dba01ff7749de1e36a000a4bdb89a6fb690450aa5058faa277861a8
  yandex_kassa_retail_sc_id: 1000196f34ff997c317278141470a8e0f43959d46f774f077d80e644d385f435c5ea
  yandex_kassa_retail_password: 1000bc6ee88f5382f59001bcfbff424afe99e7bb5e718b15743506effab2047f8cf671be8601760aae5656d44301e775c687
  yandex_kassa_service_shop_id: 10004516559f35734ab4f16bb111c6e12692d0d1a6e2ecdf6e82af9ecdb880a42324
  yandex_kassa_service_sc_id: 10002a9ab67d97631748de0aa59cb8ea495bba1f99419c69dd82572bdce735b6a430
  yandex_kassa_service_password: 10003ed27211dd32df26c8544173ab6c1a013093198356895c711fa61fe8ad5fbdf7a046cc4944628ea3b60b497b4c969dd1
  rocket_chat_token: 10000e9b47a754bbcf1f0d78cc0325e610fc7c71716bcb8b351a8de26c03a5e4dd7020ec848288487f9a6b7614811fd1a0a25df7c907b3a8e3a2894bc150d9be60be6d1a232211cf0e4640145b5e8208c91379423dfb04ac78b80bfe3f14eaa5b5db
  nnp_info_service_url: 10009c7b81875300d763dc5c109029c6d38830f4ea734064504962a0ec97618b798a4705dcc0c7d52a37d9081b574e4b87ddc199da2b111b7d9675024a75a2368356
  client_changed_amq_settings_host: 1000f169158b41e0f618110bda3a1d61027e52da1830e97ca8dbe5d93cb8ad36d949
  client_changed_amq_settings_user: 10002ace7eb3d4ab77b51eb3b0f547facffb1ddabf589ab0472cc47ebf2f20b3ebbb
  client_changed_amq_settings_pass: 1000c250c771a93885c5d56b7f8d4ac117bf48dc912050ab676662da994e604e4c0a
  tele2_amq_settings_host: 1000335e18dcb86f2adef1f8b363c63b3480fbd6858bb9a7ad6fa7be95566321ed95dda1e0b100d6e22421ce47e68f81bc33
  tele2_amq_settings_user: 1000e6cb840db61b3576d3f331445904064c89cdbc3311c576d36fee08c6aea8dd26
  tele2_amq_settings_pass: 1000b1eec73bf3dcac4d951621afb9c28ea3fce38033f2c2a04ddf427c2b8f6c003c
  robocall_auth_token: 10004625dccf265ebf2bc9a052f729340da3080fb8e168efa29b90861cee966698aaaf049ad77be628e2480923daa4524f863b84979089fd1088d4910be1d6037c07
node_comet_prod:
  backend_url: 1000d7d0a59cfbc2fbbe6f0435363192ab7f22bea89ff8b44108b87b201ab25299b3d18e5febd383c3b71e28e38096e93195
  secret_key: 1000554b39b5221e72127e27b865f6af86a7612493657fb374719c8a1167a84f2989c358379f7d33c38bff3cb254e7f48d8a
web_hook_prod:
  secret_key: 1000c042bff4dbf303a863cdbab17c0155d2152edc182f45a07bbbcf2f09b9c4b61b9d081de27e54d98d4e65996b79adf215c7139738da43d6ee1701b61eee271da0
  token: 1000714aec336dcd443d04e4fa19c751f5e3c7482324f974d8cb79af5dbdca9f89ea37951a38e697c97e94f81c39caff3c032c1f33ea0cf61a8e46617e404cff4a85
  account_id: 1000b008c38609253d9cb5372dd51e1b721d11a6665e8a0fa90c7b9d2672c721b482
  vpbx_id: 1000de410a93f8c3ddba7b7f722c53408d0ec86ac87c05cec286c95ed6d855abf7b4
payments_prod:
  user: 10004113daf8584c7a981037fefbfb7102b38677ef4ba41b3a2297e2756d99237060
  password: 1000877e54784d1346f4f6a1bb01dbebf14e48562b1cf7b26f98deeba979e43092d0
  publishable_key: 1000df9106efbfcca0e34218417578ecda434da914e68bac48d0a5a9de5489eb102e2dd7e90dbfa76fef0359e1e5efcd292b5ed8a6e4ac870dab2327643a27f89b64
  secret_key: 1000358b607a02414c449882ccbf08aefeb01782c839ffe95cca3f44bab91d863f50bd5e60e186dc7bd30d3e2239b9bbe46a2652773cb0ba8a96c950efb939bcf4d1
nnp_prod:
  numlex_user: 10006e14d7321f6774458a9e6f1c29e74320badcc7e3b35a0d27b113004665715355
  numlex_pass: 1000f7cf1b026d391a14897a2d76918df31eff84c02068f5521364c189f094efb89f
sim_prod:
  authorization: 10007413c174ebcd5dc3e56ebf7bcb50dfe371dbcc445c5a2800ddf957e3f0a1b971d1dc28ef2454fb5274895119611a4803f09b4d8e725bd6606f25b65cf0440ea8
  transfer_msisdn: 1000a53ca12d771e74446bfd0291758d0687eb9ba042e955ab24b6b2c1120b05444f
notifier_prod:
  uri: 1000c898de4c2df4203132ba7081b49ddc0418e84e26b972052b5da56e593f496ea98975f08077bcb35e24f7fa538f27ba52
  user: 1000ab5fb461e5172f4973bb355de23b48ee2b03d772dd4bfea01ea7845ac45b05ea
  passwd: 1000699d38e2a8725817f27c43ccd5841aeb215421c478a67652b3f1ca51bf065c8e
atol_prod:
  call_back_url: 100044f26f59ce2d99ad39aeeabdf5efba5018d368cd59eb16650f64131f7921bded960850e37b9ee51300e903e87a66c22a
  access:
    mcn_telecom:
      password: 10005ba46ce3159a82b4be62ee86828ceacbed0a1c8bf39af499af643322f46a9191
      login: 1000b8927bc0e099e0c0038cb6c9c1c5767fc3c775e07ffbf6809bf011eba4cf6619
      group_code: 100031e00f08fef0c6c1ef32e7e2047ebc23d066779fe81018af8c00cbdbdf5d9b4d
      inn: 10004456069e3a6661eb38fa305a8c372ad1efd0ebf6296fb3230fa6421d900a984b
    mcn_telecom_retail:
      password: 10003f8cd1f2cd7432d05215f6dbb2d629f0e9185239d640268b9209dab03dc8319e
      login: 100014c82e75fa9c32bbbfc6137b6a0994f58ce0e6e8427844590e6a370e2a2e9264
      group_code: 10005cca58c9519ced6346b03c0786ae59f15efdd486f8d96688987fc651c3f82c1a
      inn: 1000626862512a1d95c088e812da9c7f68ba0e1912c22df87a16a37a147bd5ef8333
    mcn_telecom_service:
      password: 10002f31aaa44307b39a36e2e646b664ba097e986685d6c236d93d04d014ae75b6fb
      login: 10001873e1ddf3a19885ca6f81fe6b6a816aa237742f74ae1004e9cdb419868ad62c
      group_code: 1000ea33a70c2b6c22049fdb2322d0553c897a7d5444e3b3a359e56331c4ceb5df58
      inn: 1000b44f41f2b12343e72bb9418f5ef8d73bc123a649862561a3ee4d3079ebd375c7
  buy_or_sell:
    payment_address: 10002d4781de7d56d2aacb90219893cb564025dd00faff2e696f58f122bcd643d8d8
    sno: 10004cfba0db9ebb51587a6aa028c25e09be6d2144fb4cd99d29e563941c3a64556c6aba58cfd5d5dd3112c2543a47045934
    item_name: 10007e221b8b1a3c2f9ff66647cf88acc58ffcb4bcae61f5449dd440301984d9fa36644e95ac5098de4e031f26f157bce564
    tax: 10001f2bc5469f811d2b27c935bd58244fb4387dfd64cfc8af09470649eab87674e6
mchs_prod:
  api_key: 10008fe9d6dc8d5ea6d0f917ebd5a7f41e5b9a26baaed713c734c3acf861c827ee5e4e48e58df7192f8338094bba8dca5ca70eb22206dff2871b5f1656fb2772ebf2
async_prod:
  host: 10004823206cb5699c8f88a18c50ad931fae33e3c276dffe07c55f6954656ce14d6f
  user: 100007532e24bab0d7b67e6ca7012ca4cb75ae6ac06b04231486d291ec53415e364b
  pass: 1000511b9f7bb7f692af6b64df75d8f5f44ad68a14e016a45659d18c680ac87d44aa
sbis_tenzor_prod:
  login: 1000e940dfc5d360752026c30b2d6a09fa3b2d6cb2958e0d4849dec2bc667d2b124e
  password: 10003a1038a1992bcb1c427ca8e728b5ed743cf1cc536a86c2806ed148f1d4e56e2c
