mysql_prod:
  host: 1000a39e6258b974aba3f9fa299b82006874dff04d8ff3d20f110aebfa61ed7fde06
  user: 1000a90b626f929c5cc9c9b6f5bc3efd128e0898a0a44a46fbe5839a9ae8bd074975
  password: 1000086968d9995d10e69788f84a0a8d0b4d337bca54a4cd47f5d5e19c3ffa424560
  user_read_only: 10003854c9a03ec96228228590fb89b640835b6248d5e17213838803f92a412743a0
  password_read_only: 100028f0c61a74d4c1ddd66f173ad9886a2613625dbbc74c3c6c1453e2d7e35b0884
  db: 100060c672024934538bc176393db268b07b9a26e8c1c24c836f6654e95a1e9001c3
  port: 10000051020196468f4611c561e2d6135484e6f38c98f0cf995f1ab67e70a98988ba
postgres_prod:
  host: 100031a0605bf79a87ea7b50e22a873323e88a9ece0e85cceb3786d256752471ac0b
  host_slave: 1000b05dbfe79391ed0e5736b36420b4dccb287aa30b14a4807f9b407dcc199e34ff
  host_statistics: 1000b5a99aa5ff909909199509552fce63c4a83d76045ba9cc6f712b39e93679f96c10dab8916d141e185796e76eef342fd0
  host_legs: 1000b2fe08fdffed4ecefaa349d67cd41b04a043ebc04e7a413ec0c02f11bffed36fca15f840be67932e880e8cc927af5a49
  user: 1000236ec86077c7938b8900ac12456a5e4e57b5c12aaade1bcb92475f55f9180df5
  password: 10003e8517ff03cce3944f6c7bb242cc2235a2a1e0e7d6116505ce485b55d3b376f895035193d9a20602ba074836f0fe578618304043a22aefd8f65595bc6c0b7fb6
  user_legs: 1000353e4445b360c36f9dab9223c1431284d2cbb318950cbb69c3169ee048dc84d3
  password_legs: 100005769ba96899c8ee2623ead3ed996bbe256e217cf29694bafdd677fac89e6492
  user_read_only: 1000e0ec9eb8ee94d5c5d46d4be90f55d8864158f63dc62cf175e04e958d87223a92
  password_read_only: 1000b0cb7c97f39f682e02f940dccaec38cc6b1790bb85904f66facb9ccf5c5021db5866049fa3d9ef12d2165ef134ae3c05
  db_nfdump: 10001507323423b2e86802945241aa53653aa09d982a1c3a4b164a3e841c421a208a
  db: 1000858ec7d24b32ecfb2a3ac6e5054e8e4f80b659013badffe85756e7762f95c3d7
  port: 1000783a123c7c9f354f1f86ee77d63b8b01728495c4668c0e66d5ff27cb241e5281
params_prod:
  api_secure_key: 100061a12b616d2bbdb848735022adde4eca6405e4c27e7e8aba618405c90347e1b1e4b069e1fbfb91a03d0f38de6590d8ef
  token: 1000d826227875397d496cca9f1f8085b6c547af47c3c6771b8eb25efd1cbcb93d2bfa23af74b7cec0e8640a1ca30d389404f58094eb0a15d1173c1346926db9c915
  feedback_api_key: 10001d0a2eef0434a6a1831f67be263205db83306ba48bfbf47b1d25954c82117d72
  mailer_user: 10009bd2241ded1b1d24e1ab526885b9919d32e1af2fdab943203567a2430e274c38
  mailer_password: 10005afe4f1377f10f3c225ab60f7c2415c75c5f01cb35ddb4eeb4be470dae2fe6bd
  notification_token: 100076079219ba781642f22c2e56ab2cec7440af8ede4a2e9efcef0c3fb10c364dca6ef666f5a43bfecc9901116afcab09b4
  sms_client: 10000d9a79463a49ad6af322621bf9f2ee07a6dab5d1c550d5bf2b69704295c0bbca
  sms_password: 1000cbe6afb944be0ad542068f15c9527494dc64b60ba37a7d780ac830bd3cc29fca
  monitoring_email: 100021ae14bf5cbae8f717c6975de0cdb50977bee530f8ad74b91291cbcf6a074c96
  vps_authinfo: 1000bca085dbc54a61242c220a4860dda5c11b134f0ebc38d39f8d905d9c303165b0c29af0c2e63b8781f990c0175980cddb
  sberbank_api_sberbank_telecom_user: 100027559368b78f046ce41ae3c13544cea17a8104a279528ed86c04d228a577d434
  sberbank_api_sberbank_telecom_password: 10004b98bc95fa696d22b18a77e4af80449798fb11aadb7514f30ea58c4537a60d09
  sberbank_api_sberbank_retail_user: 10004bd988c98ea5f9fc95b60a2cda33c1618ecd5f143a15266bb5c270ee50e3cd6e
  sberbank_api_sberbank_retail_password: 10005f0919b4e192466737c3c52e7ed9754e1e7e3b52e696282ead8baef4b8632ea6
  sberbank_api_sberbank_service_user: 1000f74bcb9f142d7f267499f7f110dd77afe28ee47ec718983764f2fefb8cdb8233
  sberbank_api_sberbank_service_password: 10000d925f19c11e1c780fba8e9a6cd455bd9c909a6a186eb4ce0dbdffd907e2a510
  paypal_default_user: 10004b04d6211ddb1ce88b36ec3ce31868b4a120e559a959bacb6456f689cc36778b90c0a356e139133800063687c392378c
  paypal_default_password: 1000d2555ad5bde807403e8e80ea53d81fa12ce4d217b9f5d22bbfcad345c1e4393b73e74a4ed219451463a9c5d345f2d2ad
  paypal_default_signature: 100035b0c113c5e8e5fd578e90793b516fbbf719bba8ac8d4f31d6081fe2b4464d69d3f7062926bada9f7130f9774009c31ff6b74d59a9356dcc7eac72b22a663e338fdaedc15e626e70c8ec304588dca87c
  paypal_tel2tel_user: 100073cc52cb70507dd2ec1d93bfbb7d98d677cd3fa20d2d34e315db2881b1d07836a8de390dc387664c9c95ac29903ea6cb
  paypal_tel2tel_password: 100016d1c3ccc9607387e059b6de699b5f2f4bbe49e745700044324ebdfdd00526233c53860439f118624718f498e03cf7ee
  paypal_tel2tel_signature: 1000a7d758d240b077f2d36707e2403a2a12e916a042303144bef2ff3812827202a07c0828ff4198d628f6bf5f70e160ea707c1887a61df13f33145088c4919ef41f96872a007256c2f564472d8a060a6b2a
  yandex_kassa_telecom_shop_id: 1000b4cbdc8ca0ef9fc2b517e63d94738a8ae364c43a868c2624783f5de49e5edd36
  yandex_kassa_telecom_sc_id: 1000f30494ccb387d848d933a354861866686c172abb43f4f6f59038ab83089148c8
  yandex_kassa_telecom_password: 10000fafa49bbb88bd3d54bcc16ff9234f565e58ec88d593c139215da0857f90406e8de5da43895bbfd3a04dcc4aca13d169
  yandex_kassa_retail_shop_id: 1000a2d8ada52f73cb8dd083640ed02d181073b586cca76fe0f4f5daa2cfcb796d13
  yandex_kassa_retail_sc_id: 100027677f420c50d6c45a53a602883baa473c1c7ce9003c6a321b89fe1aa7eff664
  yandex_kassa_retail_password: 1000a9a3a0d8bf5766214a2a4ec741bce76f0e2afa61ce0c5e9adee05f5ddbda57bb34edead1712073622bb720ec497ed107
  yandex_kassa_service_shop_id: 10000fb15a2d0db966cd666306ef2c5e4f0c6b11dc7653aee189c8a6c6d9fccd96b2
  yandex_kassa_service_sc_id: 1000ab81b99ab2997b5ec4412c3b99e2564f79c43a3ccf3f99172e14f040863744f4
  yandex_kassa_service_password: 1000d20f720723dea1d8719612b60e4cb124fa145e38e72aed414575df7fc4fe27d3139d61c74cee0edad8b5822cdf81f3d8
  rocket_chat_token: 1000836dc97035aaa5d0842d0151917f16b8d2de5f2382e5c21da6b5bbe16d0a29a615a94ab487ddc59db4c79dff9d6d5f1195f34ad16e07e4d4f5dfba4e60c024057f899a7c20c4b94d8a6f2041628ce4f6c588170ba9c6786a3e04ace4e34bb62f
  nnp_info_service_url: 1000a43c5626a9d28b1acf9013ca0f0939f2f713926d7dc6db499b390fa5c62482c108be84dd9d3b4c2cad8d194ad14ea83875641de02c9285c0bcf7800cc0d1b7f7
  biller_api_url: 10002d028335498dfe9be2e6289ef72ac90e0f925cbb06759a5d9e34cee2c67a6a948581aa2cdb8aaec72b2c3764eb4d3321efb94e410b866cbdbbcf56552b7bea6d
  client_changed_amq_settings_host: 1000c49d2cb708aab47127e489db572930e296ed847938db882bc51e1798624c5c6a
  client_changed_amq_settings_user: 1000af5633049efcd69ad3f7cf71509c39c7634c9243f37846525cba0e7dbb9bb48c
  client_changed_amq_settings_pass: 1000ff68b88ede392257b5ad869d6c80bba3c0463dfa92fde75745c8c83843dc1cf7
  tele2_amq_settings_host: 1000577a45ddd4f5c59bcd70b577946cf65790d42d20572e6a7c58867460e54cf006924b82d21320462c30f4e1550b03da84
  tele2_amq_settings_user: 100075e7930e9d61a0c082ed0492767fa4c2902b6acc704411a444d9756665dc0621
  tele2_amq_settings_pass: 1000f838d95d077ead142a62e513f61aa210d659c9bcb23c6033ddbc6cb2afa0375f
  robocall_auth_token: 10009b987dd145140eb5f5edf7a6e6843e5dce9b8b538972557ada27855a86754cd916d67b9361bab8f236b6353a97f22cc91bc74d1f6dd149b2636c36858351c0e9
params_local:
  db_voip_regions_r_calls_user: 100028ed2c374c31071eb107f162adfaad32816e9d262d38c754c05165ec1efdd248
  db_voip_regions_r_calls_pass: 1000921157cc9f5e57a296cd3f366b983ae3dee6c21b4ab3e7c281fb0a14a2bf803b97c1072df15a55c5ea6a150bdd1320d22a2f8285a7a02551efd27d2d87d016a1
  db_voip_moscow_r_calls_99_user: 1000a785248645c446bf9d79fdca7342fad8d2b109f156a4ec3b8135228f42086323
  db_voip_moscow_r_calls_99_pass: 100076eedbdfcdd3a15714d4f10e2658d03f9fa4518e3e3908d62eb4fdce51bc840518fb66db229427cd181cd6af956fdb38
  db_welltime_ext_sql_user: 1000f884dd7b074cca515b03d4dc3ff99df69723d4d72831513a98dc47df8f09cb2a
  db_welltime_ext_sql_pass: 1000ea86124b69f999c5584f7942623abda1c278b70f906e9a9b34d2e042302076b8
  sync_with_lk_mongo_user: 1000c479c4c4f71504cadcc58350507cfddd34a96e626a9db06b820bbbac6dcbd918
  sync_with_lk_mongo_pass: 100061bd209f72b0bc6d8891446f89851ffe88c58333045ccf13835efdc0951c98c3
  sync1c_ut_login: 1000ad374acf7ab6229884ea98eced432488a84815b6a800cd32b3ffb29cd9e30f87
  sync1c_ut_password: 10005b573391851d7c182e5ea3b1fd82962dcf7a933a068e2cf5eb25221fd86c05ce52e481632b6dc4ac17698f1d7aff7140
  sync1c_stat_token: 1000a2208b0d1030ace56e382db0ac402828116e2461e664ce7a9c2529b843a4020afd27b2413639142ac18abd8b4e8380f9f58ba346d3afc5137aef0d952a88deb070c72a616cf3b8fa5fd5cd55acbcf7154feb7df805c835f5780f41434f9993b1906712b38da4dc21165aae0a487a9c5d456dcc8f6853354912b4fae41eaad32a8fb0030914762a8acceb87e348c5b7591b90254dab3a3728dfc040dc0cb51f6f
  admin_email: 1000787e03f461ff56d91e10101aa1dac224a00d54f0891a4c854f7beaa255c60831a20a4ed61ab75ea91ab5148702731137
  admin_phone: 10008373d38cd8eaf19658fd543b3c59bf76d7256ccd5e7d64875ed00976f0c8575e
  monitoring_email: 100090077911c92d813a101c3dce33cd8bdac29459bb702e4c9013319cee96966551fcedfac4cf5ca5963e5c036c1f77bc5b
node_comet_prod:
  secret_key: 1000023f5a19ae55bcdf274943189bc8de6e0ba7d4281b0baf926890e3eaeef86ff5c31f40b12e1d3330c2d82840b9864ebb
node_nnp_ported_prod:
  connection_string: 1000bfa0f3178596212568cc6981dc9030bf6ce68c9d28088e3e974d5a3288324e0608102c0c1ea3c186ad06e0fa586c09c4fa186d21d629f9d7491d89b1c1070a53d136832948e2ad0deb77a0a08b767f92
  get_url: 1000f1746eec0a549158541a5d18a6a2afa0451c0ec44cc201e71881b306a601ec46ebae10afa5ac5e3a0ada62456622646e92deb4c60ed7460d7dc37b7f84a010b612967013e56521286413c7781196de65dd1c30753a6ff63d4be094dd1d41c7da
web_hook_prod:
  secret_key: 10006718f553df1223dc5d1069cc490a100d2ef68de49b4b3eb4e8fd39d6fc9d8b9f452f7a8a61398f35898da006d96a2757089fb782820e00107452c741be80f11d
  token: 1000cd433b6caa11473956b1696d874fdca7cc0a7c9d09fe69cb46ddb53dbc5eed3752b8af338dce135220bfcf013919959b97c6736f3bf41cc795e551ab66ec94e9
  account_id: 1000d5769fc06063a0c9ff0b1a8e267cb3deb82807572e8b3eebb54b89979a0c5578
  vpbx_id: 1000eded66efef2e8db5ee44c42dff12cfe9930e52ff20ebc751c4f2f1445e0fe3fa
payments_prod:
  user: 1000b26788e4e6ec7b2e3f3097caa8cf215ed77d014e6cf65236944a8d7a2957b6df
  password: 1000802ff64d5979ab40de2371b0d04767a39d7b540f10e3e319411e5305da553a1c
  publishable_key: 100031c4aff56e40ebe39ac01834de7a801b9ce4e0230f496fb046287e10fd7aa24ec004deab0813e197a5e1e7813bdd10d5d33b87d9f419f154c83a886896887634
  secret_key: 1000ac3330818a18a974274fbaa48a1b3501425ec51b46f5f8a34e8c347a1ab657391eef24273577c18fb4ff9d2f7c4d5e026b16b28a16d413efffcc53f91d963872
nnp_prod:
  numlex_user: 1000fc9345e5424318a37f9e0ec4daa18150dcb721109772ccf42fd12268ac0ad760
  numlex_pass: 10001bc8be09c9efdd417bbaa61cb1e3b62d9657d78335751eb33de3256826cc354d
sim_prod:
  authorization: 1000c374a942ec97003ff5974a7e050f48fcdd96a9b4a7f10bef8b070b8f7eced12818656dd6b4435000903ae001a84ac721152c220174b7c680dbdf0c74ef92dbe9
  transfer_msisdn: 1000ff5f9bf8c9e118fa4fce470db012b5d38abb8e7499952ab7aa1c25e58be58ff6
notifier_prod:
  uri: 1000b851ada71a131c1ef47f7996069226a48e431c8f86fb4b9b6ac8eb5cf259b3e3bdd219f956321e82b1c164095edd55e8
  user: 100098f312bd0ce6c7bcb409647b80aa8b374e2a6045ed5b728e162ec6079a66e6ee
  passwd: 10009f7af0a1c83144111ea5660d6e75a3ad7e2a54f05435a7ecbc15ea6978c3356a
atol_prod:
  call_back_url: 1000a89855b25ac7ea8572f92ac899df55e43dd36008deb404cc03df524a222cc93424519985b59b2b463f71c7b738650215
  access:
    mcn_telecom:
      password: 1000f22a03bdea25468fb24328d5606b54f1350259a560ffea37e7d3d101a58f41aa
      login: 10005fa99d040b39a2f5767efeb7cf6f77d4b96a050404983a3099efdf36b03e1c30
      group_code: 10006f0ac11e7eb0c05ede4998e0892a61c0681f68d617811ea9be3088e11f93ba4d
      inn: 100001bc64ca1ab33ba9c91e3fc15ca42f821b87268b0c662728915c127747e48d07
    mcn_telecom_retail:
      password: 1000a81b9f8d638df39db737b9b62e92ae3266d0dfc5b3df20b1a2f7ed81ae68f1bd
      login: 100009ed23c4c1c85252575b2e48fa7e15893f953d33fd1bece19394ddb25fd1149c
      group_code: 1000d35b3d0b2daec3d6c713cb7c9309479e58be78c064c9709ff011a5acc3fff3a8
      inn: 100040f5f15f96a51673d661f44ef7dd6b3115a7722b1b2e9cf2055c7488b7e31b20
    mcn_telecom_service:
      password: 10002b63ecb7f4dfe786c37a2cb3d443b45772fc0d874486783330ce54bfa072baef
      login: 10002e5230e1512d65c2ff1799a2c0137c66abf4affb35e92d0813c96a072b7ca353
      group_code: 1000b7dbc1e8606f829f6f11ff9adbb6ebdd8401add8790d53d813d5ee34a6c58249
      inn: 1000105b3747fcf0d5a51f34faea950e4d520e1f7193b6630f2b2a793f04e92da8d9
  buy_or_sell:
    payment_address: 100032bd46661d368d38edd0c1a5092588544dd731159d98832eaa26f1263d1ef2f5
    sno: 10000fe6faa9ebe4b6f13ded1fc3c49f0686d2ea7c51c02a2bc8dd38eb0ac79a368663aea901519e59129fe272f2283edc04
    item_name: 100069e5a7afdf17eeef0abc88b3d5de86b37f06310e828ac9bfc985f9087351ef9947ef1dab6c71d01e3e73aa52b4393804
    tax: 100098c04cfc865884d2ac0a2e7faf67fe502bf4eda4d72b46f838e72653fbeb59e5
mchs_prod:
  api_key: 1000a997e72c2b2ed7ecd7bb3f35a4827d9846a60177185b31e5abaf218643aaef5a37623955756323927310efbb556a9ed0fab4c4e16a8e2be1e5b2d61578a7a584
async_prod:
  host: 100065069d9c4f2194bc3272a2048639b3bcee662519d06bf884bbf08656371c597e
  user: 1000ce50d6edd8fa6258cd516076f8c4401e61bcd18a2687451034603ca45ae1d4a4
  pass: 1000159c45b8e2fa1e41573af7ff214c936927751bd23cec00c207fbe077de61193f
sbis_tenzor_prod:
  login: 10004f5766eb4a149e63125ef50990d98f2cc4504cb378eccefce9b95e55283d1029
  password: 10004f57133a3862e1c168573d85bdecc8f08d3dcc395cd2653ca62ccc294eae5c9b
