mysql_prod:
  host: 1000dcc865e9b6e98c9b1aae14877000fae88e3fc0cc9e91c08ddb3c596bc2b454f4
  user: 10009fe94e84a31c69bc00914cb02d194914948442c55aea577a99dce8a6d9a96171
  password: 1000eee0a025d412852bd1d03bac222d965b341ecf823ebfcfbea556a543683371d3
  db: 10006be796e5be05a04420827d2d6b186aa3a082850e57a7053f9b4cb77abc14c663
  port: 1000ab56a84f2d5fab6dd46b0603d6c1f60363507a065cdc3a75218fe4f3cc9a365c
postgres_prod:
  host: 1000d1708edf78c34ed379e6bf0724a278a868edb022739d64bc45117af0a6c5629f
  host_slave: 100078ce879764eb543fde2b5eadb123c412f2023887a1503c6b247c355220680264
  user: 10002290a7977ee5c1b3ccd89853ed386657129d7361b568f52b66d85c7d26fd7db6
  password: 100024bb4ac3d891b965d2eb3623dae50140538212ac37a866631d057972f70f5d7103bed95da525a1e816ed489d61607a60
  db: 10008bde0d2bea69bf411dee9149bd3f2e2a5a9812a3299718dabf4b2654aa166698
  port: 100038dd1747cd24aab10ddf1fee3be8d96c4b49911a96172edfb82be1db8abc452a
params_prod:
  api_secure_key: 10008bd2a332656270855b87686fbf467db1da31f23f9bd4983bd49906b182ff9f1891f6a45daa72a290f80c7f715a5686e3
  token: 10005560d171f44aa1db6528fa00ab676b1de82f7769168fccdfc87fe33910485be463832677bc5bae4ef32e6d288fb76a8f951c217c413a35604b964e43c99733db
  feedback_api_key: 1000cb08f5ab4ab18770d96b9b432e080e15562dcc9406d288f37896c8e64076fae3
  mailer_user: 100080be7eaba89d057f309101f25a0dcd740274525e1b72cb91c7e70164db9c30c4
  mailer_password: 10002fba700db156dd1484b85899e8e90093ed2c6fa81cb0dbc7970ac0230cf6e569
  notification_token: 100054f94b9e3da2473fd4c40f4cad311d8dabdab9a677738daa8cb88949ef7fe417a19d0fe33081477d67218620641ced1b
  sms_client: 10001c4c669652236eb9f9d8468d5c9efcb996900ddeb7b9ab8612d2dd316fc3c1f2
  sms_password: 1000e81925e713f1931e112a21aaffed33f5ff78be44008cfc57f1a1dca800821a83
  monitoring_email: 1000a53e9c8c0e979f3d406d3e35ef07f4ebfe1f91704ddede3654a0d2db404e728f
  vps_authinfo: 100020edbea577c7584490f59c230b687d8f5091faaa4a5dd7bca810e915726a41232b907af43a4d18a3e4172abd5d95d66f
  sberbank_api_sberbank_telecom_user: 10000ae68b5facd8fc8fbff3abb398e9e7180d02d1cfe4c38f4dbdc664589cd66f0d
  sberbank_api_sberbank_telecom_password: 1000009a0006fd63093f63f873882b2ee23cc05b09f543bd4038dc7c90ae1a90a451
  sberbank_api_sberbank_retail_user: 1000ae18681a366f797fa660e7ce8f5ca86fd7990346791e2421887d52d2f0df3bf8
  sberbank_api_sberbank_retail_password: 100038940096d06692265b7a4145d8d46bb8f674e5aba055cb4950229ffefa31fb47
  sberbank_api_sberbank_service_user: 100065ba72f3d6a30c3fec16aaf2a2c9cab13ade0bde0b7af7b67c82a4a2ba2ab70f
  sberbank_api_sberbank_service_password: 1000ee2f3b4b3a2f6a8c6b3cf9fdbd9c90ac1c3c0128dd83d82f1f191de8a1bba829
  paypal_default_user: 10000b4939ed37cc8b179a8f11b0a771f50673c3b337aa9a65230a03a23d844306a0556b018aa9099e05f38d313d63a2e72a
  paypal_default_password: 100090e60c38a03e091a3340d3d14dc49ffc0ca4fb662fc404609ac9020f7a3e77183316007ef1c5c1cb24bc8fe0d1c5d4b8
  paypal_default_signature: 10004878315e9024734bffd66db765f8f0bb1ee19426da0b4408ce691bc94c8fcaa9ddd1ef25c72c8a87e3a3f52977356399afe1645a1e85af27981362e0075674d738290dcdefafac84aa1c02d755ec0c10
  paypal_tel2tel_user: 100023d00cd0124083a426134caea2219080def0a0c0ed47ed2d45eaa76de35b8048e55d3b566c27a544709be01d23dfa704
  paypal_tel2tel_password: 100086783e6a576832a7e43a1ed41c697f0ccbc485512dafc031a200e047541585cc5c57860370036e021c46b0aee16efa33
  paypal_tel2tel_signature: 1000bd58e76e61e4e972f9363857c6bc73b9f1d2c38455ee5e2c3612f5c27ac98b051e18afc30a10614737b144e101d6c43cc95f6de9873b56d2e6b88100528efcbe5161657c5b29e7458e2b29f653c5292f
  yandex_kassa_telecom_shop_id: 10009a325dd6f251641760bbfdf3ac325c5d78fee4d212097ac10ea52548f3f2f372
  yandex_kassa_telecom_sc_id: 1000867e155afcf66cbd7f83b1b1c329f7939dc19a1b51c295abaec920aa0a50c37f
  yandex_kassa_telecom_password: 1000c1903c62708ebac994b556f8073ae09650fe993df97e72ce0796bb04fa7c09f64bb98c69d39b3b1f8a2dd8c5a277ce93
  yandex_kassa_retail_shop_id: 1000dae969abb6ca0b83e55f44494a0f0dc8230967db4b7890b94619d7614358db3b
  yandex_kassa_retail_sc_id: 1000e0dd0f60fca533b992ef3a6d3fef764cbe0cf203cb3c95bfa2b67d264f0f85f7
  yandex_kassa_retail_password: 1000c0120158b3c1f6cfae4a7e1241f86365a3a4061144288311d6b850875678f883b28e8ab74ffbfe54947c8595f8ac5198
  yandex_kassa_service_shop_id: 1000335e73108ffa625890aa9c007f99d9a19414debdf3b5d97ad246383cff8f24fb
  yandex_kassa_service_sc_id: 1000d5bafce0fa8ae145dfe9a6c3e2c06976c9085f6c3f6b28a89820931f3171ee51
  yandex_kassa_service_password: 1000347c1a395d794512780fe9060da64804c6d48edc59d74d36e0bb20a75be2012e43df4777a97f6e79c837a85918eec3ad
  rocket_chat_token: 1000d8b519a771300985eade392c7f34a459bf6386d396626dea0668e9e894b817eb9fe457d98cf0cb1450f66130f453aaef09ae30d830ec3332a2e5f3576ddeafa0cf58e12f98359ad7d17fd13c82acca813c4bbadec8c9fe5ab1895c2ce5a62af6
  nnp_info_service_url: 10000e56aa1f2cd9097928db5fd6c4cfecf81d9a6422f846d40d847263f2e3ef45dd4ec1b7739a6af0ae41e0e7fab2d975fd2ee1141c399d35482c94471b6781cc9f
  client_changed_amq_settings_host: 100095ec21a151803a988fc222b27e83316c931ce293f2eb4f3b368f7d2aaf0b51d3
  client_changed_amq_settings_user: 1000fb454333aa5a4777c32f98f40531670795e82d81fd88b0d3588df40951c4abba
  client_changed_amq_settings_pass: 1000ffc208bb756b6cb733d8fb14a634ef020992c871a992a5fcbb517a061f98f3a8
  tele2_amq_settings_host: 10009d8ecd256e050f05feecb8f8a8a17c903ba4ae542322c4181e3b52458bb65ed3ad81879e495bbbba9e9e07a73f9566a0
  tele2_amq_settings_user: 100029aba1779b772b49627addbaa4190adf063da7ed5c0e31727b98d50ffa419419
  tele2_amq_settings_pass: 10004bdcf57f1545f730ae745ac6fc5ca2ed9d03be3b70f3f000a01bc42561f4267f
  robocall_auth_token: 100064761ad9ee64dccde3d3649bbaed6aebc3fcd1f4d79c33d54584ad097eafb26ac19158251cd874a071086b47f48a131c441dbc726eadda63491fe5f6c96c5dfb
node_comet_prod:
  secret_key: 1000cacdcc6bbd960f25f51430399332a0f9994c07f58ac3baf144435957d89af590336786ba5cfd2d67289a1f020f257cf7
web_hook_prod:
  secret_key: 1000631a55f95f50a008a8bee0ff7de036e584932a25401fce4a3af47a5954e4b51597097f76bc365ed223caa8cce166dbf22bd6cc510d26e6270998e1fa9dd07c66
  token: 1000249330abce3810038e6fe88b0cbdb075bb319f0d744333e2a56d68fa35d3e56690c0af67afe1d80d47327dc9ddf1940730d86c6dd113ebea19a5e0c9f0a4267a
  account_id: 100094970c6524d95902e66e167bebee41ce6d392c983876b60d668ff5a824ea4c72
  vpbx_id: 1000224175cce3f59bf2e67ca4cf76ca793c3a603aafcb5968249291b7d355f3ea50
payments_prod:
  user: 1000447f04af98abce7d6053b7402faa3ab1c4ec7161b7d9cb2782b7d4e61805e0ee
  password: 10006d44cae0454206713e025cda7a42848fe77071a32ce8336a538f68debc9e2cd9
  publishable_key: 1000ea09846540926ef340c2b3df7e04f77c780212b838e9ddfc2819e8d92b669186af04227c145a05d236292d5dd0e033226201237820e16409befdb8e20a7caabb
  secret_key: 1000bb084ace85777e1bf42b34634dcd7e018b08fffeb8397355fbb6b560d1169c200f5d3413b34aaf2aa272fd616302a5ccbfcb9d7dac153dd6ca97069fd24e6c48
nnp_prod:
  numlex_user: 1000652ae72d17c3637f456845cbfd7836afe5b7d4cb07fac724ce675d19efade698
  numlex_pass: 1000322361660d1fecb957c8cc47114ded8bd9ca933d58a4bb103152771b652072b5
sim_prod:
  authorization: 1000eb29f43c8850dfa5c93747aa37869f81e03a46a15310a5f86c4f0134348b8f85c3bbe750bf6250e8293157fb9c5a7f3d25ff452887b1f1f2c98b5a5d2777aa38
  transfer_msisdn: 10003a62598548157e2826563f8439f6390851e0887ae8ed60df127abf0073834dcb
notifier_prod:
  uri: 1000ae4d277e93dcff705a4296110f778e0624229b346cb0ecf6d02882197c5f8d68bcd9ad9463e2d5340ddcc95ff89b10da
  user: 1000275e15f51cd44ba8bf4ad4a4275f1c6e19ddaccbbd19de6c57c58b4452c1e4bb
  passwd: 10004657e9642c9cc319aedb6db98ca18f1ecd85174cc72c6f419221e75722e33f85
atol_prod:
  call_back_url: 10007a32dcede2e7b83c54680c32076d55ffed466da54096bd9fcd670f5927f1b271488e73f0f133b7ad845f9a5ba83a0000
  access:
    mcn_telecom:
      password: 1000510dee441d0e95ce041bb802620a10d8a322d936154650cbe7a33ff4838f9b35
      login: 100032ec93fe862abba4a4616abf4ed52bb7da0f59c26563e68e6d11084d38cac27f
      group_code: 100021bd6bc9bf1c69479b03c033d1e46f6ecc08321d485a210d446dc95713a6bf8c
      inn: 1000359f59cd13c58386dca1f4d5bea211b4a0bfb6d9cb68099d42604894648d9bee
    mcn_telecom_retail:
      password: 1000d5b60bf890528ce91e0bb9689823f87915cc91ec249342036fdc7cb36e2f004d
      login: 1000774f997f54cab449dac39616199a21fba1c36b6913782622fb4e7fc9f2aad2bd
      group_code: 10001d912d492004f8253ea22229596e7e3c4431d117ce847afa17cb29fdf3148ae0
      inn: 10000b1fa00817d50b8f198ae8e8fb1e80594a25dfced63b799fbffec6d72de26df4
    mcn_telecom_service:
      password: 1000ad8110b112325868f7c66842dfd79130126670468e8a227813e876bd78e98b3f
      login: 10001ef6f48df6c1243f30eb54da518f7f51c8b0f185c04939b5838ac4e9c4bad18a
      group_code: 10006cda96a8cec004011364f8ad6693aacb090e6185b4dd6d4ed81fab6d1e109088
      inn: 1000440db09b24ade703da722c3de44e12b593d4d84a8add3ce6f90f8919fb901d7b
  buy_or_sell:
    payment_address: 100059766b86b454715846941dd6a7fe9ab7b7ef98157857ed7d2f444207d06422fd
    sno: 10000e5fe281b42ff22e3c890994834521376d91026d540f1049ad9fb239fabaced41bdc4e356d7288e69bcea739002c34d2
    item_name: 10007093d61db2eccde55034bd0f6baa60a52ef2258bbce0117b9e67f6e42cdda458bc7216c07f066d45a993b9030006532b
    tax: 10005a57176d6950f84bbce1c746df1c5a76d1618139f90e68330882675c7445f03b
mchs_prod:
  api_key: 1000b2c0c6a2a9366ee47d9681250fb3e8f791107e25a8338bea9b1d54ea8ffe58f0d0a292263cf25155ce49c01a3c68f70859953e2c9deb6d1dfff7a9ea4b4faf01
async_prod:
  host: 10004182585eba77604d9d19cc19a1dec0aa988139022ffd60abff2fe9feb70d4d35
  user: 1000007647cb192781b88eca17f7040d3a8ba7715220a3b5ae7f8a2e84adcf02887e
  pass: 10003d3ba04efd36557485813cca514be25e51968354a55aaa932a23e7d6013a8d49
sbis_tenzor_prod:
  login: 1000e7ae35f2f951ffc7fa7a477bf1d585dfe3d37d4d992f0d2b3324791c5ff06fa7
  password: 1000316a4f074b092ce9ba6e3b5c3fcb7606d4a3ff7c85d8927d4ab5778c67cc8449
