mysql_prod:
  host: 1000074ab44ca2bedd52672dbeaf339609714da64d6266f8c66ea86393b5c59c89e9
  user: 100087abe1c4a7d6047e869680baf258a0c45c000010debebd1b55b6e4d142846fed
  password: 1000b0f9f3a8e926c2f58b003fafef05a5a48708c0c1b62595dbf0d5046c223fc3c6
  user_read_only: 100029430c184ea8c6ffe745b94ca7b505f53ac7e84c02355c8b136110337ceedaa0
  password_read_only: 100026a98f38ab2a0ab246647c399112445c399487a98a3b52bd96e89b5b237d4f5f
  db: 1000c65994786cd6f7cd1acc0c0ea968da52b995ccfefa6f0bed12f56e6d4b667924
  port: 10005617b4bb9dc330f2b0f5ec5669f29c5446a6a01787d80d170a785200252ff456
postgres_prod:
  host: 10009f1735b304b92be1448ab4d7309721c289d3d52a66d64bfce2678a6fac2e5c6a
  host_slave: 100037826821eb38b6f67f967b0fdb3c457b922a43a2bb5d841a3bef5181e09d58d7
  user: 10003515460acd239bcacb2b68a69c07b15144cb91863f035103c50cd838545aba4d
  password: 1000c4ba4d7c5c82da04272d7799fe38621a4818eab2254cd7e874420436853b092120b429e7d4f368cfa96f4d5f0517d4833586d3ab8f6d64236e8a4b23cac9144b
  user_read_only: 1000bd654c42a6dece43a9358feb56aa145e7b006dc931877e662dc47cd033bd54b9
  password_read_only: 1000ba3e2a1ea0ee2133971a635399cfb263bd3c0d02d722a0b3d4cc288e6064d99e262eebc54dca10f515a02c9d3aedc6da
  db: 1000812d8974939da188d9a2f0e608eca5c21c2bd304048b6ed3099d7cf93fa3153f
  port: 10003f2b364c1efbea7bd13ad32b07b1e4fb957915828c260087094cd79129293dbd
params_prod:
  api_secure_key: 1000be4f53c99894ec8312c9a01876ed917e528898ec5f1ff98023766a6fce6674fca071841f0750cf8b4bd502506e00df1e
  token: 10001bb0ec31971131399218c33f98f744a69d5a9dac90d8109fd877324d4e791c537890175d183318f664364e36687c54312b82645d62b7c0e2e0349ec9f40240bf
  feedback_api_key: 100068a93a2de71285e212d14bbfa1f497be4686a65ee0928509ee2a6172eb19e06f
  mailer_user: 1000f555856da3aafb2ff27f0664e6ea23057e9acc0a18e9ad279d9f33de8f610f91
  mailer_password: 1000b385a12419c8fbf340ff1c9c2ea127a65ff83064fdf67570f1eb53b320886eb5
  notification_token: 10007cda0c38d215490821ff893df0f38bb025ace50ea85c03fff7dbf87841e6097659bed96b813e82875012b5ace3b59d99
  sms_client: 1000b68067f88cbecf275f98ed9123c60e68b78eabcdaeecb6a0bd1d44d811e8c0b4
  sms_password: 10007e7f976475f5340923753d5edd718442e40435c747c7c62f520e8fcb97cb624c
  monitoring_email: 100076904ba5ccbe6fe5905ec4e800c7fc869f277e41e7b4dce0b24e6a9da52cc736
  vps_authinfo: 1000985d57970f97ebb0f72bcdc1af896b8686aaf2ca0346c68cc73cd07cc57ab9b6e350d4f355a1ac32a75cf37697fb1528
  sberbank_api_sberbank_telecom_user: 1000a70488392f5aaca2442c5b3e0d4463b7426b5bdb8dcecc60b276aa79d84d4cbd
  sberbank_api_sberbank_telecom_password: 1000254bb8777b16e04266fe2152cbbc817d4dde74f2412166288ac2055aabf81f3a
  sberbank_api_sberbank_retail_user: 10006e96b414a89c68acfbd5ebfdba03cc826ddb882a29c37c5940171138d67ff840
  sberbank_api_sberbank_retail_password: 1000ce661c2d79cf72816aadd54c6a5d212705b19afb133066ab4a80be7b1fbcacbd
  sberbank_api_sberbank_service_user: 1000d2e74b266f174de1b267a7f51f1e36d290e8db188c37cfb7efac61bf9ce99115
  sberbank_api_sberbank_service_password: 1000a45d4129ed8ab9245068bc94253e20097f6b4f24eb05fced825e2ca1c3a275bc
  paypal_default_user: 100002b07cf04e2e2c67883e35c965e299bc9ab02f8a05e208efd8c570ca543ec708fdbc1141498ca58f7b4ae7c88ec49f7b
  paypal_default_password: 1000890a01e449a1c3a287347a3b2f5e6acd2ad3c7a207c2b9b72f9f4b8a3ade153b3da2bf33e5907ebb85a45c9d5fdc90ff
  paypal_default_signature: 10009fcbbb7a8dacee33da3c070684bf539dc9e740f6966604ba1cf44aa367228b6dc42d5910bd338222dcf3334e3467919ab2e714bffcf90825a10bceee244e991d6e7dc7d4bd43ee21e65f8fcafe75ed84
  paypal_tel2tel_user: 10008add4a2949e7ae9a2e4320a77712bc9a3d3d165480f3004f6bb90bc538e45ce1d94cffca19efd966536302bf41362c0c
  paypal_tel2tel_password: 1000f624007f348af5270bf539610264da97bed9d546f59c5f3a1ca9f45efa800cc31ed206b44c90bd041296d27774c0d2da
  paypal_tel2tel_signature: 1000ace9a61df583973303d7c2a8a2938a95570136b54573ec3edc4a504308e5b5f25d3b019ca00077e9d3d9bcd4ab9d8ccfc85e61f53b2c43f1a154419da4aad4bc26f731deab3fc2a5ee188f63b54ed0cf
  yandex_kassa_telecom_shop_id: 1000ab094ab78a563cfa4b43a37880d5a0c0e11496a273c9de3b1935369bf4d6696a
  yandex_kassa_telecom_sc_id: 10000668ff6b52eb0d63b56ecea30d083128c20be29ffe733ece94d23ad0208f2e2d
  yandex_kassa_telecom_password: 1000ace3f4c97795c38bb646503d90ad77a540b609af0ba97e8cfbad53eaca8b0547c0c440ec76956f48a7d3905c12dec037
  yandex_kassa_retail_shop_id: 1000b6abb3fa669cb9f798af796eb157f2d024e69fe47d251861a5eca31c7f6397e9
  yandex_kassa_retail_sc_id: 1000835d0d78f98d5d7934acc19c3c4e1d2ca24be47ae73c257cb21f4809f38ad234
  yandex_kassa_retail_password: 1000431615b9e0b86b13a84615db532139afa12b625fdba2a1a3806c8731f071bd66f7e6c1ee04df5699db3dfca79829e1de
  yandex_kassa_service_shop_id: 1000ef0f32ad2cc11ea57aadce9d2150e704dd6b0dcd631ab301465a6ec259e022b7
  yandex_kassa_service_sc_id: 1000d17847b05eb737f3b80cb6199ae488e42b5e15947b0f7724c54f213ade11268c
  yandex_kassa_service_password: 100051a13b2e4f1387ce64c63e40257f67cbc82abd1650c0a42749f332eb8f431292baf717ece243cad1499360b9325b23df
  rocket_chat_token: 10001a05df4f5b5adf59b78898ef5e4e6011ae39b12abe5941fdb3cfa40bb52353f02450263eea6fff2e46ad2284872b8bac233bb4799dccdbe4fba53e6593b22e864dfce6c54add915268d92c807e94bf7a005f7f7e351bd74f079b1d48ee256337
  nnp_info_service_url: 1000ff8a0ed82103fcbc3347cea958803137e467d2073c67299c203139f4071d14d0eba4f8728d9d31f320f28b7cd3972512bce8d17aab919883c940721c4bf59049
  client_changed_amq_settings_host: 1000ab2b94a16397ea1eb6c0b5d6eb9b38cf86068d6d9a5b43c1d38b2225f0316468
  client_changed_amq_settings_user: 10004c65b2bd92bbc332d48c5cc948ecefc7b1212eb98c721564049e5aeca368b512
  client_changed_amq_settings_pass: 1000bab048149f703d09b6b6c8ccca08b4712c42ec49eeb1df3160dc52fde9400b78
  tele2_amq_settings_host: 10000a750077ae1a22c14da6cadd4bd7d37f69144fdcb32bc24b242abce6c2cbdf8df0fc2859090113185294751b61a974ba
  tele2_amq_settings_user: 1000ede5f1e6584c14778411db06f67b50d134b1bb5bb9510753c8ad2f0e56c2a6ee
  tele2_amq_settings_pass: 1000492bffd7515e1659a1783dfb3d4fb2815731344cf8bf1a6cb79ef975dd4e4607
  robocall_auth_token: 10005a82a3149351f1d4e5ecf1bec322128511901680e0d4ad9ccbd887dedc48472e48e5a7d200ef2b7cd80a83610e8fd8de8e93d00da3a2d798d9c816cab5082753
node_comet_prod:
  secret_key: 100087fc2ce848caa7f27ca62060a1d67e72da6a534d761f84222ba53865f46bba8449a0844b2041bc711b7b89d90dc496eb
node_nnp_ported_prod:
  connection_string: 1000878a4a21030239e07566441d2c98bd87c4360c5ee1192bf168f32cec0af845e02d8765d972f5ba7a689dd872474ef76266543c905c6f02d8a3d5690bb2efce04e75629528d351f93e7e5d6da40b92ea0
  get_url: 1000be70d5f9618499b4ce61999108c51be3f231a671e738eb9d69789c48490684c37043381a108b00d0954e5ff49c4bd4138ea00aa79ba8ca1fcceac344cd23e504c3bf568035c0dabbb2626e872c3b0966c75bc4230edff56e6c57ddac6d803306
web_hook_prod:
  secret_key: 1000aaa000a2374958721d532ac5b65b344faae460bcbcaa9c3f14e5d5d65d377604e959b8bc4f50cd5aab9f4d95d23bd9ecfca4b5122ca942491f8013cb75416776
  token: 100063900f49b4c36d1940fe0a0a7dbdc62ea0276ddba884242ec838a7fc9ea28349d54d757d66ee3c9f514c374d661e96d4e3fd96b108467c6c084c3fb2c5476f7c
  account_id: 100049e13fb37588e98ba1cc5d17bc37874f27c1243e240eaeec0d30bfb3414216d5
  vpbx_id: 1000a061bc33460b0555298734d3164999d3033c490dcb89deea33a4afba3a54e87e
payments_prod:
  user: 1000d5f52b63b48092e020acf3fbd1b04d5af0291b9e1c06c0b8b0414930c4dd44b3
  password: 100086de18a694ab0025314211e9b1a6aa25be76fce678e9c937b26af8443f511c5e
  publishable_key: 100092962a5f4beb8902ae2047e94fadc34646aa0d3e30c52f80097444b7098ce5564e5d18d180c184e438e0da3dc39c39333b540475cdd65e3ae2bf5c06507fbdd7
  secret_key: 100003f979805f3a6d432660aa56df1f3eb856ba9535ccbeb727a9ae24487a253a754503387f18b2ed485358b0aeae898163af1efa6b4e17acd347a72aa1c77b04df
nnp_prod:
  numlex_user: 1000090b8080d93faaeb88eed613654aa42282b4d5f1f71ea0cbd8185b2031f5c0cb
  numlex_pass: 100020eb28701f562192dfb80defaa195376554c8fddf5bf8b0d9bf29114e165e05d
sim_prod:
  authorization: 1000d4efd6e1c1822692de0472ae4a4700d01c36605d76e88e23c0a63580c8d7fcadc8d52ad9afca2f0cf38bb4d32e7cc027632fa3831681c4d74fb53e48d7723660
  transfer_msisdn: 10005d6288231451260a667895c270b91ebae3f9e9130b089db7736913e216637946
notifier_prod:
  uri: 1000cb5f62ad2ff0ebd2d9dc56335d50dbcdd658211c5abd8d099938a41ea0fc91ee8df5c02eb6f89ed9f53e1a138b823ca4
  user: 1000b9482fd74fb5b880683fb61a3b267b581a8754ac26b56ad61faad9bb139d3431
  passwd: 100064ce325d92438d114f984f7a1cf18c2ff5c3d2d2495973aad26546a887af60e7
atol_prod:
  call_back_url: 1000fd40daa0bbdf160ef144f0ee77a3a1e29a4a89257db7f19770c6dcb9b503563ef92e3ae817ee5ec7b1417f51436f5b1f
  access:
    mcn_telecom:
      password: 1000e25a3994736d5fe3aeae9bddb0ecf08f27535208e4726be92facbbc7b93e4d29
      login: 100090ecc4351344cf80e0198847bf1c7b9321af45760b27d82f468ca7687d4665c0
      group_code: 1000787d1c170bf4841750eb7de45a59acf482264c82405a106aee6b43fd664752b5
      inn: 10006b3d6d0430915c41cb88a227e194217d2860ae94d841383ee4d5045f306fabc4
    mcn_telecom_retail:
      password: 10008d2820c4c9ea8ec5b5a6f63a2d5b1d4b7e1a943ff5a59f5293f27a613d93794f
      login: 10001eec868a552439ced4d314ae9282c51e6afd2bc836649ff3b0362b63ba6f86be
      group_code: 1000e8b9833d65ebcc544fdcc38aaa03fa798a33d78566fc7dc0a23c8047212d0d1a
      inn: 1000d881755b919d950c4fce086db5296ad25c8cf7c2c79bd09071e534780a9e08e0
    mcn_telecom_service:
      password: 1000d818a6b1f4bd1ba3aee9660ee4ae78556aa3f4075a5d499d6898a70ac65421d4
      login: 1000ad30e97b24e5c5d44f7b7d4c3c662a147c6c555e2da4438734e9bcabecdc3451
      group_code: 100076da7620162acede1d3f8cfa6bd24abfb4250f1247dffeefdbbdaf97e5f6a095
      inn: 1000df5f8993c6c2eac7f1b662afcf38baebd24ad2dc82e0b032a032403206cdbce3
  buy_or_sell:
    payment_address: 1000e208d8fe0e979d42c8a0c10c609aced0df1288daed887da610137e2c55ee181a
    sno: 10007cf4af55a61f42a310b60cb547952635e6374b8b467fb9541b44019e07c5ec2d7e0827584db8713c977e9b8045a7ad2e
    item_name: 10000fd3514eba690ff93dd5d4610f24543610afc388324861ea6d7edb18b10d672d2166bd17e577738eac8738bd95a2ed18
    tax: 1000c20cacb19c5478a45f79b25a75b09e8e052f5185f1f04075357f01e52a525f36
mchs_prod:
  api_key: 1000b2a3dd07503c60625a572fa85cc4abf257cf5b168520bae98109ac0fa404a70d7c6b71136f50f4015b2a24932866000d57386211d4fff241f765e62b9fea2ad5
async_prod:
  host: 10009545ca308d68f43845969dbc11f772a792d46020af1adaf9926fdbd1d1fc51af
  user: 10009b93690533ed448590cda2a3f04639082bed6e6ed5246ecdd7895632986a1034
  pass: 1000203f58f74cc2b4457b54bba76e27d5459dc62287b253ad408012452fadb9ba84
sbis_tenzor_prod:
  login: 1000d9e50f6142464355a95b8ea18ceaaef77c5eb6b7ec342e0e8effd76b55bee0f7
  password: 10000a1e1b3ec8934d37f569e5da2dd9e4314360a46477076059f52701ae9619c152
