mysql_prod:
  host: 10000cdbe745a6f9e08ebd34415881b1ef11b3ad30ec51d76d8c4e75c1dfe2aabbd6
  user: 1000b3d40563fd1952d17fbfd95f7beb83d844e33cd356f7cef1839c3ccb822bbf42
  password: 1000fb9e40600e29ae604c8340de222d6cd5f203849b591c9d8a0fc7c2ff1927cc2d
  db: 1000a1d6728c2092eb2f8722ee7ff0fd0e6d75c8a8f85e0c25e0caa3d6a9bd2c7351
  port: 1000714a871160a6fd599f168c18c0282afb281bf23f9e547500adb3d3c5e7bedadf
postgres_prod:
  host: 1000558dd650c06b4e63c7d7de8121bab1da9c048949ea3b3d496b3dc6ec05b1a200
  host_slave: 1000adc9d2f2c68ac365a909b39e0c5b3d87cc9c58111149e4a9d366a38a6205a2a8
  user: 100090b9a17bb21b6d21f704acda6146158c8c4e9c72cb5f1e14c08deae53b9d6377
  password: 1000b8172442046f9812a4a2fa46e08f709c5c6c6e26b785c025db31d24c80238e24d21589f373ba7b9a181b4fd9a75b11f23067dbcdf0f1526a985e2a37c824a22b
  db: 10008155e4dbed5f7bd652d7c00c23f59356a320693a606dd607fa30bb1101afdeea
  port: 1000465183487266050918ff67c2bca47c5f8fb1d01176013dfcb700f9e7099f6f89
params_prod:
  api_secure_key: 10006791620edfa2b3e43ba7adfe736736a7d72db392f0b50a31ec3e3d07f51ee648a2a0ebb6e6d18461057e114fb656a226
  token: 10007aa5367f69a319680881fb0833cbc7e494861ff6136f3dff2800ce963db3e13f42ce50f7dfb174eee91066820f2eaf0d3004afb94c56356266b432352189c657
  feedback_api_key: 1000c56cf710f3ec295fcd9ee9a9e89ee7b5f09b28e956f0851606ab1d09bf66da10
  mailer_user: 100079a4bcbcb15456aa51cbebacf19c871bf59e0f9b5fab738b29b39660a67e5056
  mailer_password: 10005d3f5913c475d1ee15e18370ca47cb4c73f3f24223081d2fa704570a441fd9e1
  notification_token: 1000bf64ceb20a25a6a612aa6d8e03ce4a34dc1e1b20712ce68a248936716bd46f3822c0abbcfdf6ae4a490feacf2649b7d3
  sms_client: 1000db936a815697402a0f19baffab675ee452ad20c9ad469499f5d75bdfb2532c22
  sms_password: 1000e7403d228504f4cb13915d83f0a0de57bad9604778d04956911dfe9a2c36ae7c
  monitoring_email: 10002e372063e1e0ead27de6a377df9014e2283d1a4ed4435d3b59cf311383c4ac1c
  vps_authinfo: 10004191f06df38f628d64cb519f12c61f4c5d16968e99de21708e30a089ea2bc2fbae7dabea5c7c2d47eaac096df50c0b0b
  sberbank_api_sberbank_telecom_user: 1000f1ee83eafa89ef6a132182b68187e6bc147d5a14b6d7f356bd280b2eaeca2ef5
  sberbank_api_sberbank_telecom_password: 1000d7c5c38c505a2410872aa37092645fc326ec65b2f6217dc61dc3cd93b227a817
  sberbank_api_sberbank_retail_user: 100017c74c834c520a1ea7b723037470e84e74816fd75df3cb28275c815b4d7f47e9
  sberbank_api_sberbank_retail_password: 10006b9c4c40e16840b4774d2790c9af9995992cb5a18f1837513657071384ca303d
  sberbank_api_sberbank_service_user: 10001101c3698bdf54e6577d183adcc9dfc640623a56b3569e04f758121e4a49b150
  sberbank_api_sberbank_service_password: 1000aaae091830645155d1ede19bf911da1586c1ad568157c7574e1d132b4ded4fe6
  paypal_default_user: 1000c39f63f07dda0ba40355e0618372bda4ac7b2f69062c69ecdf08a5bd32357e7be078aab5623bb5f740d25416952ac25d
  paypal_default_password: 100025ca30ff5840b0f9cfa5636643008bf6fafbe496995ac466b1a11c8ee1b0e668fee434dec896c30c8120e5af8ecaf8b3
  paypal_default_signature: 10004cbd62fff6d0d57bf06dc82899af3a6ac76224b5e8a7c69a5fba56c87600358000f18dc188bacc06c944399dfb5c03fa3d9325921b04e4a5437d19eb3f49d12e1ee4c2c65bf40c3e0010f7effa5fe6d2
  paypal_tel2tel_user: 10007e178ef1d7d84d71111062149772d7df3e0436de9c8549d910fa817fd66d28cfa1685d4ba2203e92f0263800bd639cdd
  paypal_tel2tel_password: 1000132dd01e5ebb9ac00b6aaf28deeb444b49c7e16e05b11070dc094f5048923f8008f05893f284865e350b3d5726a16241
  paypal_tel2tel_signature: 10007fa811ab0e3a1205a5a209ca022b4ae448d0e4ec80cfde88e222526421c7dd701fe9882f46454994204d34d4348301341de9db1861d4649e442390e2e1d6c504b33a3c9c4188545093011a0aa0cd6288
  yandex_kassa_telecom_shop_id: 1000fcbbe5d69c4f4dc2e7954115120a75045f08d4a167d02b1909134ce2b17a8c3a
  yandex_kassa_telecom_sc_id: 10002df6591ac0435cf356e7d99e8c59c1cfd83210e30f8e658698900fd595dd903f
  yandex_kassa_telecom_password: 1000d56349c532fb4f99728de2744644a122879bead43f423939a52c563f4ff3f6e808b94202fb2f043b93e0c040ba70aa44
  yandex_kassa_retail_shop_id: 1000423b251e773821c86340e067f860147fc9c71beb267833abb5d813446796b40e
  yandex_kassa_retail_sc_id: 10007eba9b12b721851dbc82c9285923eed63541b8bb4cfa59c272e4e0380b047804
  yandex_kassa_retail_password: 100024d0b404c6b2370240732e1a57248e24d88c999af82fdbcf429f084f7f7e474629e04a0b18946ab1bfecfbb336464945
  yandex_kassa_service_shop_id: 1000c1d50ed9dc974952cace938a2fdacd8b4c7c722ee8ed07fbe39013fabd13848d
  yandex_kassa_service_sc_id: 100092b82abf442da49a4b7e467dffb72292a839d6b593ada3593adfab5e73c86264
  yandex_kassa_service_password: 1000161def023d8b24ac3c466c239f84c4444e81b1951c601a225194f7a2d2e48e65cc710195ed6ab4f1e4ca6d39784970ee
  rocket_chat_token: 10005c15cdfa1bd235f919d0c85f3b71f5a0989e5d9ab91269530dd4587ed36a60d3eb39993038bce03206d3080fbab2d1d272cc97f780b7cec5d388ab4696c531620dd022403fdee7d99b77346d5c09359c50bafb1636c55a5255f7d523111c33fa
  nnp_info_service_url: 1000c1ce6afc1611ddcf4538e1fa4132d6c28c30f3e7ddae73d4707483c0b52dac81cddabd5efcfa98c604a03f25713802c856d362135a58b11a9ce6533f12377cff
  client_changed_amq_settings_host: 10004fa3c0f7e9f3d4e206ee45d0533eab5911578e9cce91221ae8f18949f5ee5f34
  client_changed_amq_settings_user: 1000b75be39e263f1f806999dbaa7c06d774d559cb88aa5e2e7243e41a470856f1d1
  client_changed_amq_settings_pass: 10001ee99cf7c26e8a2a59148c899ead2934d84dd7493a796e9e81525a4fa3c24b9f
  tele2_amq_settings_host: 10003b9404e62bf42c2af212367112b0e3505412f89297b9cbbd835955a669dcfa8b27f358ddeecae5bb46687ea5296a54b3
  tele2_amq_settings_user: 1000b5ce25a6ae081bbf542b23fea37cd8bbadcd41a8075df6e800dd6e745d9ebdc6
  tele2_amq_settings_pass: 10003ec009aaad0f8dd47aa7f0596f89805c6b6496902bffb87264104e70c35a1621
  robocall_auth_token: 1000f88894ac8114af7811216b1f5ffa077584f2f64d1047bd743e54981dba560a17f162419c248b66bc9980fef29ffe1193feba7c53fd1680e278c9b1a4cd083b43
node_comet_prod:
  secret_key: 100072ce625d0b057a3850a3c4e1aed1434d281dc8273d54d34f9a93943d04f00a9780666d1ddbf53afc45fd7c6c04c219b6
web_hook_prod:
  secret_key: 1000be5b08f888c1227aa2d6ab433789580c0ef66303e5085abe35f33f8bb83c96b547d72d6fe585a9016d996ee3eb85751ea77a3ec096bc23fdf50dffec2e7c2bdd
  token: 10002baaecd2bd0a522646de51876a63f5ff916b73096c92eef41fc12cc881817c184d9d801601c918fe9181bda9c1cd10c820827b00765f798bb0e2562841ee2046
  account_id: 1000f2c687d662406b770f97f774fa502522da4bb79286c120dce53b4dff62f8b72a
  vpbx_id: 10004373c4ed9191f6a61a54bae11da8446d77d64dc536904401917d0217246eefe2
payments_prod:
  user: 10001037a4fcbb1ed82c3319ef5e59f9735fdf8acca0810dde16e019e7552a9deec6
  password: 10001870030322f4274b9b0f7d2f5aefe31abfaefdfcb15b3b6d540500eee8277856
  publishable_key: 1000cb1ec1769c003b55b22ef4cab160be8045afa45fa2e4f91d15ab802f67f326f53e2fe710638654298cfef99c0ae152f34e8f088a702019907c00835356b7189d
  secret_key: 10006e9eaf09d5df6f5f428f8a998b07d0c5d2f237c57418e6cd2a158a17473ce3c520c02c8b35c41f7b01d596fbcc71275560e1e7dd5d1be935d4bc35422dd8e569
nnp_prod:
  numlex_user: 1000f710efb47d006cf6f06662d587dadbc5a36596d199d59b3ec8971cb041996191
  numlex_pass: 1000a6d6d7d6f5e7355d7c7ac7612de30672231c9a8399fe96f535db398f0c3f0f41
sim_prod:
  authorization: 10002b59da53d7063d7f23fa3887b04d37ae6042a5d309979ad877a8050f95a2a85b794abf45996138230b3bb457de1db2030d6e94d363eac8aafc6c53784ab91555
  transfer_msisdn: 10008405bcc68b70e9b9ae8866b30ce8a92ec46d623ea11f979895588063a7f42208
notifier_prod:
  uri: 1000ffe3c33633c18af462dee934ec0bdcac97cec6be2ec4fd91be3813b62f8e6784a4c95e81645579ed819c8a8bf9b92b3f
  user: 100005fcdd6f83b7e2ea8e3a8d52dc391ca74db8a3207a1125bf4b3f1470ea1102ba
  passwd: 100092aba60737281c6911f1f24da1eb7023bf60d180cc02e5f0798f3d888f7b0138
atol_prod:
  call_back_url: 10006d7faa764c4a1c1dbb180ff2f0bc35f74ad229e209c1277ac4c9a6ef3371f398b7d9d1feed1ff2319308a30ddd3895d9
  access:
    mcn_telecom:
      password: 10003f1e9351f88447fc6c5f7f4b0f0c8d2553fd3fa44d5ba9cfe5e9f67319897e03
      login: 100051974e1041ca327292c6505e7bb4298f21625c34bd79cac53b5f72d6c3554c3a
      group_code: 1000a954a3488af72cdfcf50fdbead4f587f6ee657f233a032e5beb15eef6edfec47
      inn: 1000c244bcaa39ee21dcd5b3082263cb270ebc0031292077c17b3049af5a0c9a1a1e
    mcn_telecom_retail:
      password: 10007cea17dd534e9b4fa4a9e1817656d15d12f1d2298a897573062869545fa3cd9a
      login: 10008631a50173ebd1efbaff903780a57943852797e359b87a9543c4764bf4ce15f3
      group_code: 100068cf2fbb55da8c4974618c20ed9f55bcc30e3efa25fc248b0a8f5a998bf37249
      inn: 1000c8269ccae710af6fe5b05bcb2776b0da77466401d7c71a3bb9e3d27fba9aa0bf
    mcn_telecom_service:
      password: 10004a7c3e251e2df95945681659eca92b6d313c668055715c1ead3a9282fe908349
      login: 1000c37a7f7114cac3b7bb39f77c5edd4dd87eff59cdce8e965ad59b42bb5ff6d3ca
      group_code: 1000edd48a89f461fbec9d0376dc4c83b9bc23f756141a12b506638827751a4c4afe
      inn: 10001463d1d5bc718acfb80adbff838c8b3ce5bc79beb073fbd86eea1f16476b717b
  buy_or_sell:
    payment_address: 10009cc1544545a05fd526a19935633469c470069cea69e1ed18d3e4580728dabcc0
    sno: 1000520cb79e63c8a6001149e9dd94012a2f472880886e6c6ee62cda29f299f754186287f57f86f5c6f7e78100859b08816d
    item_name: 1000d8ecdae7e76e64136eb0637bd07e0e3196ec48fc962de2b77f3084f69eadcbdb89a1314b4c8c98383b3b129e344c1e49
    tax: 1000000a15f39fbad27a44611e6299ed433e19932147a8a7e38fc690ee5faf7d8b67
mchs_prod:
  api_key: 1000e01612db8efac007a3c42db9d477b9ee554b4097a3015897b84d66bc8f758f637c9c9d9feaf05f4d5f34f5351c8e66b6abc74b08805ed5aec53fed7d8cd41fa7
async_prod:
  host: 1000310e55b6867e6d6d62a1715343ee220576218dd2d21ffd7f92e811cbdbfcd682
  user: 10007edc341cdc3b3a6079bb9b1488a8e40985781191b671e616b010f3974f5a0c6a
  pass: 1000c574d652c636852533417db14bcd86967d7194c9b58d75c08c524586d87993d0
sbis_tenzor_prod:
  login: 10001c1532fea8cdf82a4d2c4b41a7cb1c12152fef06c224ba7070a248f4efb1e5e3
  password: 10003512f2d2754c477da99f9a01ff0ba61bf4bd90dbc1709ad95d9f42bf230b78a4
