mysql_prod:
  host: 1000ad710383858015e880bc74d801fd517ee0f2f787579ca083e7d0977a168d5f58
  user: 1000adc534421dcfedf7b213c7aaa7fbecb15c6194ac8bc9ede8bc6627a38c8c0472
  password: 10002fc1ec7f02a9ca81735dd7ec4ba5a1cdd5a238c4d7ea535dba87fd94e0e1e4bf
  user_read_only: 10004ba7aa5b0b435c089cbbfe27b29a94e0e40ed08acb28fa34c0a1844d5dd78495
  password_read_only: 1000ada7522dd101e621fb7ab280a4c4568fe693c8a88d1995b30ef2b278943a0ce8
  db: 1000cc5bd5d7e1d37dd24bfe97d670d8bb41643966df6699be8fd738d051e7268f6f
  port: 1000ffbdfee0b065e6c9b4bf549e0fbc587ad29a2b2af0c53e171cacb5429c1464ce
postgres_prod:
  host: 1000d78a11b1e244587c4494296c89ea1fba0ca0b35f075e7c883902683bba7cb9bf
  host_slave: 1000344e689dfa584eb25535d329683394df4eeafa77a12052b18baa44951d8f74c9
  host_statistics: 1000e7db3a7948034d15c291ef91111bc070e845aff2418e48fdb8fe9940c776953e339cef6eb8a2493cc823662f057b6292
  host_legs: 1000821939c776fc217badc3e3d66be943b106257108e2a2bc0b7b3d5fc9c6a024a6d051d2835796d30c343a77f1b17e18a2
  user: 1000958e78138c3e2b58e2116d6135876783a32ffb1d25ace3e0c4ee6dd969e9a292
  password: 100076c50a42120f355b57acc4f0644cac9bca6269ce27b8727742039cb88a8614eec46c0cfd9a0aa8f4f4a6ad43dec30571e09a58025924f2e712bd29a2c4239090
  user_legs: 1000fd0cb59a1776b3281965ef57f339287f9387ed04da56ccd0f9adf4cf40690b80
  password_legs: 1000d567a91113f8547394f2e0e72c9695a8454072d8a6fb39cbfa8b55497e725952
  user_read_only: 100049aec2772e1425bc4a1259867edc17bdafae4d4f13d8f14a8b5aff4f7bc21342
  password_read_only: 1000de51697d4e04fad98d63f9c1f3515158c299e793ba88a91a66d31cc4dae3a9093c51b56a7bdc91391dd43bc6b8949e63
  db_nfdump: 1000f31831954d7ee6e0fe8793ceb705c4c5358816bc46e08ef602b817c049b28b5f
  db: 10007fa2e8f2d114b128c7c144ba818050f0e5dee7c637229b9893c6a4b297c82e6e
  port: 10002e9ec1ce083f6abb3849069bf68d3a011a2b1ccb186032c4fe46d06d26c82ac0
params_prod:
  api_secure_key: 1000d8e4f364895a77bf1ace301485d64ee2e505d6ebec3e28d66fc1a8418c3f93a26dae27e17d099829845517f6496734aa
  token: 10008e8f88b2794237622efe138320e84bbdf8ce4ba2353f5bfbb05a29a59d049e0e24e23017b9a7bdcd4261277167ac709c7d47d9e9b3b64d89f576ccefeeff9b71
  feedback_api_key: 100066a54cd0526159c960ee18475d15892110a65bccf2fc6d6ce572f1fb760c1515
  mailer_user: 1000a172ecf410f8029c60f8afb270761667b6bbe35191446ca853104126793e6a42
  mailer_password: 100060dd766339586edeacf89e1ffc6c6dd02e51f8efa4c397ba6af63684236cc69b
  notification_token: 1000931da46479fdd24ea576a297bb92b387c266f7a3f1b9f60768d4266569f6fb9bfa7b3088f9209de29bc9184a57256c33
  sms_client: 1000c5a2393b4c955cca948ed6daefd14d15e97bebaec64f97af4afff93601c5f81c
  sms_password: 1000760028916529d1980c8defa34804aa0a093bcc0c3e7f52ffcb0ab04c32cb29c8
  monitoring_email: 1000ac01b79a9bbacbc34cac4fdc933abf793b2fa824a198632432fa9d0f9d9de8a0
  vps_authinfo: 10002ad460df4729f46893ae32674a74a7c7795133ae824c683d80f74379aae72e4d773a41dd142c17aa1a307ef6a6b8b007
  sberbank_api_sberbank_telecom_user: 100048e6a47ba85496338e8d346a15321e285230c055af90d2e683710063e0a36527
  sberbank_api_sberbank_telecom_password: 1000beb395da844d25853bb8f3ae718fc1450232d3ebf4986e382216674e6bdacf29
  sberbank_api_sberbank_retail_user: 1000705fa0d0ecc3af9708cdb98b780ac295570104018919a79a8d449d4789da5dbe
  sberbank_api_sberbank_retail_password: 1000ab8b16d5907985714f36a621946a2976c5038ddfa9c683956a6d4c53535e80fe
  sberbank_api_sberbank_service_user: 1000e3f1fac5f8eef7f2869b6acf6a7258fe516e3e4299a4886a53c2942826288c06
  sberbank_api_sberbank_service_password: 10007256b805ed4188bc3bd8f53d157ba6473dd20178edbc9494c1e9b2b1fba4607e
  paypal_default_user: 100058b00dde2d4d2ce97c88d6cff77a244ffd7616909debe4c0a62600eacd0d7bca0374bcb9ea6359155a06cfd501e55d1f
  paypal_default_password: 10003764aec74239c41bbbaa2963a32a7d7f573e77f00312f697ec422f559261786c29c8f553e83748cad73b87869c5066f7
  paypal_default_signature: 1000f2eea1ba0af52c7516760d22036b7ecd11294ce8028c372b94eb3bc826ecf22ede7ffe2eb267cbb64f19b13257009fa011279f95563852eb1e56b7ac49c03c49be8c19503d67f034a1f5c092cf6460fc
  paypal_tel2tel_user: 1000e615996dbe607a4d29895e53f5029ef92c38fbb39ff0b188deae231dc8abc4026936f3aab274cc84c2f99418df2c9e2a
  paypal_tel2tel_password: 100031955f2bd1aa49020454affef5f13df16b8ac8d0b6b9a70d7ee991dd2bf81c52c4d9c2ff523a1c17cec35678b9249acf
  paypal_tel2tel_signature: 100052e341358aaf229bbdfd550049b1652af8cd3b9fe2007ca5403ace0fc6bccfb81c7c2426a6be8f2e95f81c86160f551a340e472b12c82be2621daae2c81b81f5d957f510afba55d5eb07bbaa4fe88f75
  yandex_kassa_telecom_shop_id: 100079a90468a9868192e50f92b4feb9dcc6406a860843513fee3f1818dac04112ef
  yandex_kassa_telecom_sc_id: 10009a196f8612dbcc733c6fa5349d08fd78dc14a9eaa5cace9237d6098032d3d3f3
  yandex_kassa_telecom_password: 1000e32cd2d31413c986659bec5d21115fef54934bf964139448f28be8f34c3103ed3714670dc71987ce449e0a20b5904979
  yandex_kassa_retail_shop_id: 100070087903fd3095361f35a57007297b80479d394cb07d451fa8c4fa7cf064660f
  yandex_kassa_retail_sc_id: 1000d3a6ba6859fe21869012499e229ff9973cbe288e8db0704140bdd6a21aac99f3
  yandex_kassa_retail_password: 1000d1db329f74c80fd1bf301e481ea1dd8ce6bbf7f2a9c8b545260cfb5407b87a049784609ed95efe4105725dc947cf1eac
  yandex_kassa_service_shop_id: 10002764c971ced50c872756b86937b34bb24d116a2b6e3013abc0c6537a974885f8
  yandex_kassa_service_sc_id: 1000d4ca69803192d146e7515e06105895fc974e53b48ce681cdb7f37d04115426ce
  yandex_kassa_service_password: 1000a043b9d8b4864c8e152eeb8ae1f51d86f3ce2e711dd5c3d96471d67777c7687bbe96f96ece3c575531395c9470232138
  rocket_chat_token: 10002cd398a8adc07dc56025dea800ed5c79a2378b29baf57a440a7178fd02e41fd6b8f05fc25cf3f83e50bd6d742529e91b039908ff8f3f9509afde323fc1ce82ac9a127e3a98b7f7bdf389d7754e4f4f74ea59ccd185fdfb362c09ec43c16fc148
  nnp_info_service_url: 100081ad5a92d3d9dae47395bb21b659c1f839b0d77c45b00ca982831a5b099a8eceaa9c53401fbb6f74f3a75f01c8e313893c75455d8e3d5b002303d85c56d88831
  biller_api_url: 1000a35e83ccba914075d09d915bf00f0f12e2f238867640b361613ba52c7ab04b7a4507e8069a5e3c67ede89d39113e2acbc8cee004efc8c4dafda00f3c4a01053f
  client_changed_amq_settings_host: 1000fb9412cc5efd18f21fa2e3d274f34a59c10b26046e32d07ecd072f95980e3ee7
  client_changed_amq_settings_user: 100085605c9502693a740ba5f74c89e05ee1f2c8bc76180d28638c010489b3f644e0
  client_changed_amq_settings_pass: 1000a9acce851a92ff8c7a34877c49c2ba56d314b6df166288c1ebf0db3c3f91e5ae
  tele2_amq_settings_host: 100098039f613972143a288bd4cf26e2f44a266d464863ba0ca9e333399f24c688b3e8d4433ba0741114a341bbed0585c879
  tele2_amq_settings_user: 1000388771f82391ce8ab8898df39c3f29a248ed83d60372646691265c52e8c69e34
  tele2_amq_settings_pass: 1000ef897382b40bf857cafa47f724d9c1fc58294294cedaedba0d35402dfa38eeef
  robocall_auth_token: 100015345e47ace0e1e4808a3b5d0e3e62ce156252df39717584a7d2fe7b4135d3493df5a5d755db5ce5f44c3ed1059036f9ce73e8d36423f7667ffe5a06d78e8d7f
params_local:
  db_voip_regions_r_calls_user: 10004a98c121eab0b448f1bb2a0cc716a48fc86ae4dcea61f19bb93146db56558735
  db_voip_regions_r_calls_pass: 1000ed1cfacaccfc27e2284a2ddb10f7d3c268a684f7074abff149c95310956e7fd59a2eb14ccdd53f23b5e81f262e2e546b980177d6e22c61b70e56a659150fd12a
  db_voip_moscow_r_calls_99_user: 1000826695bcf11c5a162b6019af021f24cb6ea23a657ca31341106144627405c916
  db_voip_moscow_r_calls_99_pass: 10004935144451be21c0ca75818ecf9b97d95c7a4a92ba7c31a92e870268a964d4de36d05784a59a181c09fdb961d85b7085
  db_welltime_ext_sql_user: 100053a3c5a951f1c27de85a29f71e2b2f8afae5b9f535b633951c92aac8ab1399e5
  db_welltime_ext_sql_pass: 1000e5d3665d23eef161cbd0c7de46dc4110c4acb1f6ecf5b589a83a39a4b43bcf62
  sync_with_lk_mongo_user: 1000278fda56053bd65708ad139ce87693293319a8ea197a97c210c1122781ac6ab0
  sync_with_lk_mongo_pass: 1000aaa9be1eeb801c8ce2f2bc49f95ab1a728a866e3438c2bae1fb79862923b6a62
  sync1c_ut_login: 1000787a729537392ff5bd0133af5271b92ceccd2f51739a80e030a9edaf8ddf4871
  sync1c_ut_password: 10008e21677a6a4dde620b52717ef02a4d768f410cd8a7b49673d93cffbe5fbfa8538e7927b900257930958bf70594aa9a7a
  sync1c_stat_token: 1000a74c7182ee19e486ced39c5a0b2519426b9e37fb283f45aa8b90ac6e7b8568b51fdf27ffa4983bc6609412f28b44050bc2522c04ba04e8d490e5183492d2a9509856547fd5a0f92a8ec8ddcc5ac4054d72ab4c241ebae2383424c3e26a70dbf9904316e39d40f3795fc379ca22ba56aa18718d4ee74dbb1587e048da0c6776d2a1d412551efb36d408b9da7470bf7e6b9adb7db5df533c3e5f8d11e47d135d49
  admin_email: 1000ba8ac46903fbbca40bce08c127464a2b97a52db7f20ea0639f4f0a40f76c09e70dd5ef132838934cab15bbdeb687c018
  admin_phone: 1000ce0e974763050029a9f6c85d7eed40c6a081c197045bd95f601c0ddd550db03d
  monitoring_email: 1000edaeff52800ff228d19d01c38d2c93925e0eecdd0fe7636d81abc8de5b121667d6cd8ee1a072a0137430681e19efd636
node_comet_prod:
  secret_key: 10007bca57b2dd74ef9386aaee00c66cab4c8c0053adcecd06e57497df211316a4ba9bb339c689d386c295e4706e72f2587c
node_nnp_ported_prod:
  connection_string: 10001380ec1679293bc020f645af8ee555bc030388a2be47192bb0962c3e1cdce2bfb461c2901283dfc0bbe29710ebf4ef404dd6802e09b75fc63c0aaf34290c784b496968c6f3f67c7f6647ed6ba369486c
  get_url: 1000faa5df77c0b431ceae58c9e699bb2d5eea68ae7f7645c2be4e1c5cfc2677a9b8eb2eef3a43d9e0e114697e606429edb03001ad5a2708126ed75993107f59e9dc792b60b44d7e52a108fe9af6501cb2b5bc4465f2ebb75d142a1e8e0f983b2a02
web_hook_prod:
  secret_key: 1000d93f27c182cc2da361c977164d294125a9aadd2c0d459fd5cec80531ea8efb9c8dfd72ecb41893fad725f7217bffd2aea8ab8e3e64914f1479c2b28f08e03402
  token: 10003b5118096302a63293ddbf476b1f95ad8b7137065a785f323fdd0d7a6b902f882471c83ee62f50b53960e77fd9c3a75e940ce580180d7cbfddd4a5faa0536b46
  account_id: 1000a6ba8e29f83fe5d3698156bc16e8e97f570ec22e191e1b4dc260e0fec4c16567
  vpbx_id: 1000baf759828f1da15be8b75a6c4c0f590bfd5faa73f01ab12c4fcfb5ab7e6212ed
payments_prod:
  user: 1000b0f3a14d081176905f5f6491c834b2ae0537d60d4cb3e1483d4e454620ad1c37
  password: 100006d02a6405cbd575390a54bb92c4507ef7f5beb9a138c71990d0a0053a46b2d7
  publishable_key: 100079d0390ec91f067822202bbbe2d6810a95d78f5656ed6352c4f6574353f48bf6a0421bfa15f01e68a7c01629b0f0323348e4ce8468baf44380a13293bd0dd7ea
  secret_key: 100089c92c0e7c98d1bd5d8d7ec507677918c911d50a9bf993b917f7ffce618fe2177d44d8d635ccbcd653696dfcce66da60f64ba08080fa31826d6eb89b83c7b68f
nnp_prod:
  numlex_user: 1000f618f91e3ce22180a72579c18849e847585b82a6438e412b709c9f5a25417896
  numlex_pass: 10006ac85649b0875443f957b1a03330406849cabdea7d5064067efa4e141601aebc
sim_prod:
  authorization: 10003a4ade952d4dc193322f61a8291c15ef910a7fe46127baa848c245b4fd680e3d88cd5adfbe9d87b9f6dda273f1ae8b0fe7090750e76124759dc8d7c614aadb07
  transfer_msisdn: 100011fa06c64ef4b678fbaf4ad174ec6733691246bbe70868ae5c6ea26d4ad2f6a4
notifier_prod:
  uri: 10003fb40ec040f363d1c8f0449a768efa750ee1a633cb160f9019b6edee20f2bde6ff3af3574a6074020084d0dd21ca7082
  user: 1000e45c801079dfc53243fb082af707108323403f5b6bfc4c7752268e324414754f
  passwd: 10002ae81c5258b439d5b08d21b7bce48a3ef511121a453481f2687b0763746bbae1
atol_prod:
  call_back_url: 10007b8b2f8869ecc57d130ffa921af0d6e53faa751d1caf9978b31f5b94553759e41895bcb937206153d45e16496d759b11
  access:
    mcn_telecom:
      password: 1000c88d6cb44657e68418f9102be413298e2da3fec2368f5618e1c26f8387f5220d
      login: 10007761f9b13e0b614b8d9d08e1e17f4f68ce4a1e6a63297d2bd9e6de88ea162af9
      group_code: 1000f717e90a5dc82e688af78e8d430db75e6098ae6ffb3712fd7a26ff36d8f77cb6
      inn: 1000937db274d4eed5dfd7ad72987778aeda224e2256458d287746eeddf0dcd1a6dc
    mcn_telecom_retail:
      password: 10006333ec14de0ae42ce08ba3a01a94072f906e5f13fb96a2b4402a70380a45ce3e
      login: 1000336e050a6ae640bb5df8e5b608b2502421b9a68e155c07f8c9aa01e3366f46c2
      group_code: 100063a7a0464da416b0a1666a81093547753c71e1388ad13eb0ac4188ecd403a320
      inn: 10000c4d142314f234c7532666baf484c911118c5d828a829e0cc4ed9f2923bb1a0f
    mcn_telecom_service:
      password: 10005c20a1652b22f8651504823a17451c3fefc77b3dcc7893014b58739a1c1cb1ca
      login: 1000de658c74dca19914b2a30a6922086e24179730403d2bdd34713fe7135ac5b261
      group_code: 10001e1111d81c6150721c83e55972d030c911cfc6e0daf75ff443deacf26296d5ec
      inn: 10002332b6fb92f2a1b8002f22676610ac3745227ba30750e411fac7a47bb80c0986
  buy_or_sell:
    payment_address: 10000e3c77fde9a23fb37b3913a24a4f3822fcf6791dff4b758e19a37f05d088cf69
    sno: 1000eb54d5cec0b9b65369594a4783ed15b97bba38d073586420fd12168bcde031e189e9968c7d56f7b4f2bb1459b7380f63
    item_name: 1000ad9b551defef34f9e17cb9902ba3286e625baaf405687eb79b308a50627c77dea02f557c7c45f9e31799a0c82b31e0d8
    tax: 1000923bac8aa4bed0861e158b555f475219166bc4ce5258abe55dc1e8c0b878f9f1
mchs_prod:
  api_key: 100013913daa6c97fd2a4c886736e217e682dfc56035905ba5e2086c186218dd9580b27558c941d6e9e4c9fcd6b52ba30f2c2dace8bc1e280653bb9ad323183b3670
async_prod:
  host: 100028bd7d1526fe8b568858d071225e557d97e5e013ff152a79cbf75a8b120f9708
  user: 100057126175757408feae6652cc2ced6c18c81288a5b2f3252537e2c9a891a23119
  pass: 10006689e0975c364794fd1a6370916c600819cec726902b623a0f61ad18fceabe26
sbis_tenzor_prod:
  login: 10001666f30b8c326cf8834a1e5a8b97d446c95264abb17fe93db0249035712cdea7
  password: 1000e7d2280f65c38dd6dc49a54e42dd0db870aacc6f54e01a420766e3e9958ae695
graphql_prod:
  user: 10002cc392f4fe5db9fd75a692eecfee741ed1463241d562af039c438c20d2518174
  password: 1000f55b1d2413641f0f717e518202e3ec57174fa903b19835a5b512818519862e300c29c4182e53982f0516c63b41ffe5cd6cc7446875c2e24efb6e55d6293d3fb7
  adminpass: 100029e4505f42051dbfee1ce9fa4abb80ed4b5beb6d32527c3e2f6d775476ab7eef
