mysql_prod:
  host: 100059f513d896824cbfcd54e4e5a8ccbed71b13632e9220ab5a8b9b5334ff0dc509
  user: 1000c5fb4fc33e76583ce198efb3cb864af38e03d84a927218ccaad5b85e92ad5889
  password: 1000615f18bde3dab0aa128b5abf03d65938cc2560d2dc3125bfecdf972ea0f328b0
  db: 1000b051607d7408162e8d7ef61a39cce6581e87cad6361d069a3f5f315aeae025a0
  port: 10001f3b8b55c5ca308b198bf1927923c7a3b8cf6a5fac13d4da4ff0bc84114d820b
postgres_prod:
  host: 100046060568bfa4494d01947480e4d5b2ecdd3328a386de5a66b1aa57894cf3eec2
  host_slave: 1000bb57bb2edd9c6bf607edf4f1c3f3771ffdf92763b6f164b130356d2eca083ebb
  user: 10005182398916198a1585a3ce46c40b1e4e5f78f44ed99f287178eb5d9fa206d63f
  password: 1000b1ca091b3d0f48b29f8299c64613930b1022f743955b7bf11cca773f772abd5a05df6155fd374fa7da9abc78658b0863
  db: 1000554abbb9b93f86e04ab3f0934a16b5387ce1139d70b6651b08f5739473acf1a7
  port: 1000fa15abffdc1754674a035a2909d9ba7ce5273ef730ae77a1a1de270d172f96a5
params_prod:
  api_secure_key: 10008b3df6fd8e9fae20bb6fcae911f7927a2eeca3bc955958b673673e3916ab4664361bbfe30d60945a822862ef698fb8ef
  token: 1000c3f3f2768d239568ffa270c8172af2edfc4df9a45bde6ef8ed55a3d3fe28dc88a2f732b348d8e0bd1a987ff2bb18ef97e6ea6f8633aded82644878f09613995a
  feedback_api_key: 1000d5604221305b21941fdf6c1a0a29ee4d464e229a310298e4e6f793c3f6a6a8f3
  mailer_user: 1000a3ca5daf994b3379678e8129545f38df073a83b34b464d1006b3153120bf41dd
  mailer_password: 10008b7776bfc638f5c5f423186171fa06b196b067abaf5cb6127dba025a86d31c65
  notification_token: 1000563b29094db576a738f704890172a6d5b3cad58f298e3795fdcffd171a7dbec41e34ccdc07a19ad493ebaa654ea6fc18
  sms_client: 1000b229caab4fbcd40be8cf8feb2018d16e51911c509d556e3d5fbe22145f27f7b2
  sms_password: 1000862a075cfcd2cbcec8ce2269d001d32897ae82cac58f907e94c866f2a6c17508
  monitoring_email: 1000b89d5ab3ec67daff2d21e07f6ed20ca2141b241ed3b05f22f558c2078867df77
  vps_authinfo: 1000fdc1356d2c672a37420671fb87610dea31ca4427ed0198a476abbdcf13f4e1ad50fcd8ac5d4113b2d2c8329b23ddf97b
  sberbank_api_sberbank_telecom_user: 1000680a935d4b5475e18c51ec749c2433c82f4dc0c3af08e7434e11b71bb588433d
  sberbank_api_sberbank_telecom_password: 10006f5e2dd637884c990d0ec56b010597d116dff9f39bab2f9c8c7bb4c403463c7c
  sberbank_api_sberbank_retail_user: 10003405159f39cdeeaa4451af917fd46c13b2aab8f1f37e1a5a84d772c178d9db77
  sberbank_api_sberbank_retail_password: 100067958f27180f428f2c9db6b6d893e9f1ae339e968ede8d540dfcd21578a61acc
  sberbank_api_sberbank_service_user: 10009732205f4c47a5b9a07aee86eb5f93c76ccb2ffaf2eba2dece4d9a61416cd110
  sberbank_api_sberbank_service_password: 1000623fac784b5386c087829a22f00a9ecaee1e45be47f6baac0f2fe6214aed5866
  paypal_default_user: 1000e136371e223a890ce42fdb09e695d7dfb0dbae35b4911e4835032865c521fa615e50f532f23fcb7534edce4b9c84c778
  paypal_default_password: 100009c9021d48784ae6b407011144607173141ea094fd01798cc484c5c45c4c7e8d7b0ce3a395de32437134a186f59d74ff
  paypal_default_signature: 100041943e9c40b62c0fbea146ab425e4c6dbf3075e48fae692475650182751faec9ae39b66da030722f344e745f70d701237764cdb2b1912d0dc744b798d0a9be036f0d1cb8b45a09b5d8e2709a9c016cb8
  paypal_tel2tel_user: 100070583dfe78bd6d871585bdebb90f568316f688d3255c5a8775ba041470cfb91c62e081e0855130f85b3eeec3a0819cf3
  paypal_tel2tel_password: 1000e056f8bfcca4f0d3b2f8fbcb32af2a863bfbea6a21b930e4f0fb02b51aa521121598d8dbb0b64617c40608c1fce3abfd
  paypal_tel2tel_signature: 100022bf894a0db1b41bd71d5597b36a040fe6b9fc2d627491f4cfc182b0ba44ef05a246993def8fd7557ed779cff177ae6b690120a7b0b252277092870cfc1cc8cd19fc9ab0e286dfd217c1737b0ab9d23f
  yandex_kassa_telecom_shop_id: 10004372ec5b50b32c6d29cfdc54cc21cb0e7377c9232648874ef3e229b42f89318f
  yandex_kassa_telecom_sc_id: 1000c6f99ecb154856fa678b0e6e8a3909ebb75a512850ae21e51e44c3a28d3572d0
  yandex_kassa_telecom_password: 1000c92d8ff8959765c8d28daa71de787e16069a7ddbbb05869b5b2bdf6f210ddffcbce0861605badabe6792afd9a207f1a4
  yandex_kassa_retail_shop_id: 1000fc9e82230f4abc816256659d85adcdeeed173705ec5f82d5b6bb8368a66dca6a
  yandex_kassa_retail_sc_id: 10007323b27f367605e5889860102cab8c1b3de4656deb1db3b45bbcd82083a86cb8
  yandex_kassa_retail_password: 1000955b4cbc91f965933db95bd3510cd8cdc562102a3edcee3bd2d7da56b7ec21837d44b27301a1c2706a5d76549cc05dac
  yandex_kassa_service_shop_id: 10009e3e8f3f129be0e7a3b3f7ab3bf357bffcbcb16a1f1eb2eefd02b71dcfd79aea
  yandex_kassa_service_sc_id: 1000f75cc1044b8ff21a93ad98e013314abc3a1cb227ed62476ad4d867355edc6adc
  yandex_kassa_service_password: 1000a49cd42fc7db5936c91d279f59fd15915d16769137102f79481bb393b0ab417cbd184e1a809e8b97a13c63217ab9a45a
  rocket_chat_token: 100047c636fd7489817772b033b87210e9b2db7dce1cf3cc7d9bcbd1545fca16410f1954069de7c9405d398f1ad5d9ed877933d3a4810105c114cd83d8c5e321d3e86afbec4f11e8c5721b47b580d33bb55636ed626e4eed7ede214c0616619aaca4
  nnp_info_service_url: 1000c33a43ce82e7c9facd2a5cbf4f351320f0a27311b301d8f67cd78407976739159a3038e37bb4c60d1a253ffe70bd23852a1e2565358b64fe9e55e801fa7c300a
  client_changed_amq_settings_host: 10004dc1323e2de09430864122266f3e9d9c9f38266e87b70e26aec844cefc6f8e15
  client_changed_amq_settings_user: 1000b8c3cc38c99bfb1afa35cd696588a312ecb9ff52d2224a78e83397ea97a3f574
  client_changed_amq_settings_pass: 1000a4fabca309f2496cfaa24d3c04376cb07a42b5b041bd0facdd91f9622a04291d
  tele2_amq_settings_host: 100087771320c36d27df913b1b0faf2bd255e20d5657a45803f05d17014cb528c33fe6b078042d3d486b9d86a1933ad6391c
  tele2_amq_settings_user: 1000c72a23619273f5d5d66a9820defe4b17b5b85cf597b1766117c9840cd0bed821
  tele2_amq_settings_pass: 10003ca8d98dd3fd1420a389190eb269356582c20ec6c21afecd4fbd0b8e85dbe744
  robocall_auth_token: 1000c1a58037568401c8f9cfe5ab4ee9fa7e5bc85569a6f8b51e1868b50b012d15af7a8072af173fe8d3227a2fc0db3f3688730fdf70646663f64938e97e28b28269
