mysql_prod:
  host: 1000b273d7c21ff9af5c59e27299d0ee8ff216bcfe0cc9fac4fe5c62e2a6fcb599c7
  user: 1000497574a8bcbf1972a466f5b1ff5e9c8eb749ffaae642d4d9190d52ce280e21d5
  password: 1000b1b8b3df34394db042046cdfac6ceb662ab669367662834a1a3fdf1d39668661
  user_read_only: 1000657f7c129f5f6cad096cb4b31aa9aad95a25a0e9bffd48a7a2ccfe2d9b0ee0b8
  password_read_only: 1000cb68a5fb3e1fc1a64b3ca45f039aabc96d5ba0b206bcab5c402d8ca445a14163
  db: 10007887e7d7f0306fc94edd16481ea012f87c507d1732b7256b829e1665e5017bc9
  port: 10002b584535abfedcd511f771aacc0588393c486dc39403b59cd14c4c94006197ba
postgres_prod:
  host: 1000ae4b563874e082c1cd436c6b3b7a9bf0926028b928a04aa1779ae3eb56da8a9e
  host_slave: 1000764c084a1027df5c8b6a262f29004459aa235ef1418ec78a5f242f19e2020736
  user: 1000009d97718b7be9c8d263c7f18823c1737931caa80b34ba90fcb4c9d3646437e8
  password: 10009e2ce3dd7b2fe3e324bebdc74c11fe325b3b2651180e7bd1bee96b71aced9b2688931028ccabac54cafdbaef2ca029875d5f2c389503e65dc70013eda57e99d4
  user_read_only: 100084cd66f6b1efc25035513e0519ab4f494ba33097aaa0bd95c805c6a6638e4aea
  password_read_only: 100065136bc6dabf7ef63f09eadf41eb2f69bef7f2bee525ecae07e246a2c3c94b19130e4931e07fd6e528c2185b048b4194
  db: 1000da34bea48b7f8c0d4facf72187d302a98399154ca6640d693bbee8c42257f51d
  port: 1000f518dc331ca970a613d1a99352ca37e64bdfdc37ae8bda01ffa89ceef711e6d4
params_prod:
  api_secure_key: 10009c8965057993de3f4ec97032ebfc290ce3b153be1e3a357cceded7cd578d38f0c6e0d63f14c033dd053676bce71586c9
  token: 10001598c0df1f8b10cd971b8d69a9a9e50835cfe212c471ddfb1b6058668874c47d34364c48f9bf652c9d41639d0ade767c0684f20f85b3d2281feeddea624679d6
  feedback_api_key: 1000ae022782bd65764cfe8099ab4bd339a69da1b277d92bee87d015b9de468913b7
  mailer_user: 1000166b3aad6a98cd38d5e8d4b2b2224ff3257d8e3575f40c05ec277dea920c3460
  mailer_password: 1000ad201280ece2817ed0d2b25e20a5f96746bb17863ae1d57bf2c90accdb4b8853
  notification_token: 10007723abd6ee76300db9b5208eba6842f4589aefe7aad54e21cf2242cafc4e93d0f9dd8719117be5dd8621e4cd282c8668
  sms_client: 1000e00933a066454a632a5ceddebcd699999ad867ee6165847e50db025e5331be6c
  sms_password: 1000ce7cf346561f1ddea79657bc3a6adbd9f5acab6e19e221f00603dda06c3d1aed
  monitoring_email: 10003566c92be1d4e1d7d2707658b5eb20523e68a7d3a69b5923c795b96f45508678
  vps_authinfo: 10009d3c73c178b03034b4847a557cf15c3f77e58c796d5ca8467c8918d831f692a667d5315bcc80d07451a9f0ef366c9e5b
  sberbank_api_sberbank_telecom_user: 100095151f1299522c8eaa35b8f360af22d1130382eab6abeeb3c72eb56d66547798
  sberbank_api_sberbank_telecom_password: 10007ddff4a1a0b10d2e332ee772c48005eeea37aeb3e04dfdf3e8ae6dca8bc0803a
  sberbank_api_sberbank_retail_user: 1000e7e8762c750d9ea2dbef4ad42e4efdd205183a9076ccfc6387ad55f5a15681fa
  sberbank_api_sberbank_retail_password: 10005be463e43fe722c56d2b534678e467dae0f58cc8ceabc98099debe44be05007c
  sberbank_api_sberbank_service_user: 1000b4b7f53d6c2312c91d414c68237c778d41b34afb2123cc012af262e562739b96
  sberbank_api_sberbank_service_password: 1000105902c0028a3e841355ab93f28e4d30785e625a7a20159c5ab6b69051ae2786
  paypal_default_user: 10000adc7ab9549fb7b62f685fee62c26aa4b4d23cb56d6dc14ba181fb119395ee97a04e46973c66b84d8f57dd477b6b04e0
  paypal_default_password: 100058ee28a1572c26c3b4252c6fbfb4248c021f4625d31e6dcb90aa7d34090e8f973e353fe07a6263a0842a4b48d7b54269
  paypal_default_signature: 1000e9861bd640a9ef0b52aa32f9d3b7f0f3c395a9f39f96fc2cb3b2f7ffb6fcad03238ccc31df92edc4fac6e2f0b08fe03ca9d6ef054d9ee606e6e838c9775d12648c38bf2ac6c21fd738b9515e62de48b4
  paypal_tel2tel_user: 1000b724e41d32e2fdb8f45b94fa17e59a5b66bb626640cdb9deb2139e465f4c925ee8612d0db7af88c2ec24ca548c624c05
  paypal_tel2tel_password: 10006892829fb449c0246e60aaf06af087c974f86fa0fecfb887d73279b9717825e0374b3bc87cac08d646b7a3375dc8a71e
  paypal_tel2tel_signature: 100074e267585b2887c17dd8ddac5a8aed03221d268dbeb508396a44781aa3b2b3862853fb4b62d4adab97d5a3b24b15efe9a4dfff7d4676bfad5a0e7298e7a409e5d2a6dde98ca97f58dee3b528ce62d1bd
  yandex_kassa_telecom_shop_id: 1000336dc13783664d5b92803983550ea8497319dd1d0e47ce3417616c6800441065
  yandex_kassa_telecom_sc_id: 1000cc71f9ff4f37a904ff0d8c65e600c1b0321903d443aff87614a7783f2832c565
  yandex_kassa_telecom_password: 100021a5a44072ce88b7dfa5383d2054cd54575ade65318b9e12c791480bb58bda4f5e55ba00c9fdac8763ed69bcb0723103
  yandex_kassa_retail_shop_id: 1000489ed30c6dc475c22f60711be0880e0d32823dd7ef7c93c0529a17eec1676425
  yandex_kassa_retail_sc_id: 1000370cb3b7b5980151879dab82d43e20054359d1f14c4a7a8da7a01281566dbbb9
  yandex_kassa_retail_password: 10009a7a666f51ef280c50d9bdbe965a84faab23fc603a802b6d35a1e9776fc7593564ec6ae3ac99bbded8a3441be930e1f9
  yandex_kassa_service_shop_id: 1000a117916fb808a2086a640d936a893ea4792739c026b207793f4325070011a2f2
  yandex_kassa_service_sc_id: 10006a5f362fff99f5b13a5243ca7f2de3d555678a308768f4492ce6721387a31e6d
  yandex_kassa_service_password: 1000723f45f5319590e7cf30fe65a857613f26ddfd289cce21bd7ae8eb13be583f9d1998371021a9acdd0a6199b297d37d50
  rocket_chat_token: 1000c85dfc266c32765635a66da349b3a46a51280556a4bfe0054b3a160bb96b91bc3de6eba97822ad15983e4d0aa6b6b832cfd81ff84835cf249c7d6881e901d4247423cbe197f916024d36dc83223df52b4afdc696f5dd281d04e6e2fa07c0dec0
  nnp_info_service_url: 1000dcb31609a167d95335e83a573e728908bcb743295f45039bc6299aa831f9851e344d4a630264a4d0ba92b3e3b6687d81d13d310beae5b4a697288870e655896a
  client_changed_amq_settings_host: 1000824f8f1e047ccc4f9e5c329b40f9052c7fd9c362004af00aceacc490c6ab4cb3
  client_changed_amq_settings_user: 100014c932d1d822a49be05b69228b3322904e0de7fa9f79ed751baa6b5633d6bcc3
  client_changed_amq_settings_pass: 1000881245579a2e9dfb23e42173297cb969b526614c2e9a26639bc97c4a5216ec26
  tele2_amq_settings_host: 10008b9697a2472681ef22a8e1b9fa38c6a8652b2d714aa8d21f14d7699c06d4d8e0926f6522f01139f73e442ff771aa181c
  tele2_amq_settings_user: 100061affc3d80e63bc753e6da915cf4d24aedccc6cc070740a5112ab9016c60cf55
  tele2_amq_settings_pass: 1000f0b19d17c8f7925799a921bc3ab30b7591c9d91676e8871e48c46ee62c46ad06
  robocall_auth_token: 100097a0c2e215dd5110668d32046bb1efa33afddd04471770d82d43925e1ad0b88aaf714e17dbd35ba9b5a2b19dbe7c841481812be6dda1b2f55fd51ad4d30fb84d
node_comet_prod:
  secret_key: 1000e36a902191ca105324efae708124401c54367a50db1248557fe40be302e243e0fd7875a8b453f347bf9f22fec3728e84
node_nnp_ported_prod:
  connection_string: 100024d823744666a4e26f32d39b5bdc73a29c6ad004ba00fd2f028d5bab26899122ed05b0473e13b42b1c2abb0dfe7cfcc1c78d9ea02b4c0a94968f33e36f25e70caa2b3c1462801a1b4ae326b1ce4cc7ac
  get_url: 100081edddacbe12c3505427b3d5abb26a1dfec1aeed8e58344d7030632e1bc11bdab1e1f1f05f3dbb3ba487fee6d1c20b18f047d4f749a2927c5993107f7d68fd655607c41c278baf229ccdb275e66994fd13adf0558cd8bca79a5a109fa9022d15
web_hook_prod:
  secret_key: 1000d16df3188d4c0ffc94a8abd0e2070c1a86f90d9c3b68a0d741c624e755241668fb332ee49bbd00f418a175e7f98fbb2147fb7383a3aefe8effcfa6666477f690
  token: 1000eb5c2eac9927f002db7dc255b19290300a27e5cc2586ce9b297c8e58a95a75006cca4fe9d0e68d00fb737646439cad6ca02b3aaa1b65fadabfdda1963e488dfa
  account_id: 10005868e31252f1f0d7fdb5bec6088bb77bd662bd6218cddbb537e277884901c20c
  vpbx_id: 10009ce9747775c3d2a13c9ebca071de3b7c556827211ee83b9eaf8d2831fc0082cc
payments_prod:
  user: 1000f2bf91f2ee26112e0ce4682841e80a6185b28418ae5675dece81c405555f6cff
  password: 100020bfa132d4f77519032d38c3355dcd210d3247afd67e64dee4b78c40d57435a1
  publishable_key: 1000b87fa52f4036a58c59bec3933a02909797706d01365964e19401f6a716c723435160ecd804a8676082685a397d1300d28a6eae9e95da6f6d66e24ffe1a7ce540
  secret_key: 10007061de6d5bb8b1a334bbcb2a5142f45ef9a1727d42aa1188edecf1bc43a9873e4efd1eabe8505fa52277bcd95453de79c01969404fe40a60f9d52dece5e8b3e6
nnp_prod:
  numlex_user: 10007edddc1427a71e8c13f6d49c40aac2f6adf8e1931d55e311f00ea89bfe751093
  numlex_pass: 1000585e2ba47b6ae87cde97248dd907087be379d279396ffcc53cc69ed4b455db3e
sim_prod:
  authorization: 10001aab988e7b298c8ea6dd2b77993054696e2510685ceeb04017f576ba05f899fc33f2f41c664152bea51641c65ead5b3d095b55c4cd007fe5af8fe2411bb70065
  transfer_msisdn: 10009a10dc4e15309bd865861fbc5400e9d3ef6e1a1273e8f3430e4cc3b2f9dcb69f
notifier_prod:
  uri: 10003b9410b1d289edd977ddc0be39adc371f35464923810fc2e91da672c04772c78f5d5b0db8ccdad73d98319df11b55202
  user: 1000d5e2c202407d777d08ece95c894018fd160bc6fc3e196244ebd4f1db2e054b70
  passwd: 1000244b352d40fc5144e6310cecce5b945b41fdef64b3c2f386363ca0f963af71de
atol_prod:
  call_back_url: 100055a30c90fd9aeb1a5e4e01dbf98dc87f68e86fd5df7d64139d4539044fba93880543d4d359198ede172298e1d97a9e32
  access:
    mcn_telecom:
      password: 10005fb91317c5361225325dee6a036530acb6b07df914164ef20c7d37411867fcaa
      login: 1000ff91b7c4f0f48f4c602253823b8b8d3fffbd8e7e1d61c9f4f9e12391baa2451d
      group_code: 100006d8e36b86fbbda983d581f5f0a770ed742db6b092244bd5fa265bcd6f1c01b4
      inn: 1000f18bf43b913a929d22eb0668d1ca078a8815b9fd8f71c90770e65a4f5edf1822
    mcn_telecom_retail:
      password: 100014b827b8cd0e8c980027444e4a19e5a89b231dc2f10a8b832b100fc001669c43
      login: 1000b819e21f53364e7159cfb9018d337557627124848a07320f2ef839e3e19860c4
      group_code: 1000451c081a40215d10a510eaf462afab1a333b72eefdd37c660234c59c840b3cfc
      inn: 10006d2457a05e17bbd43b7bf6e7dd2da11e4eb8ac23ef8d52106216b10e6b95965e
    mcn_telecom_service:
      password: 1000217c13abc4ed0dc411e5832dbb16c8f61dddd53ccf8bddf338880c88bb2ac963
      login: 10006df8ba35a01f309ccb65e9113afa39b0442d777f2832e8f75a533779e572b818
      group_code: 1000a03365e6c72b5ee1ad8a03995687ca70e00692730daaba83471b6f2a75cde768
      inn: 1000a8f472f40ca906bec901d2d03ad4ceb022fdd490ad75b96c03075741127b7703
  buy_or_sell:
    payment_address: 100018b477c4eefc33d3dd55b9bef24147e5e9dbcca08df79cdc33dc7afef8193644
    sno: 10002419a545d2d28857fbd1e54b7e741d22f069b1e6c8126d4d2043b08092faaadda6b9738fb3b9f52d22a4ddc04d7f5973
    item_name: 1000f1188c440ee03b02714e18d51a25c3dea994367130fd9639e4b715420d4f9479cd4ca9897a56b66359628b7d239a33fc
    tax: 1000ce0822a2c801396a4cbe020c9c32c76e6bf589d53e5494abb8b1b9dc3a9be374
mchs_prod:
  api_key: 10000b95ee60bc0002bbe4c47e63faea5ab53b10b1ad7b900f4ca71060eea07a98f3e0ac6a0e8c4d5fdc1042c931f8509a31995c0cfcecaeb82e826bd41e435fde28
async_prod:
  host: 1000a90444577c9efea9bffefc81926379e428370d02dda00ba18c1c6775d4b84420
  user: 100012e3d8dd9d567e6f901cd51757ecb8f08dfe5f096f09c5279cad8edcdffd5418
  pass: 100032cc89b57a727be8fe0bff2ab31649750e666dd83b22122fffa59fb7d0bbe417
sbis_tenzor_prod:
  login: 10004cb8df90fe5dc93d5461a6307a9a7f6873fe382dc4dc3cb9844dfcc925a2beb6
  password: 10005cab1a4c620621c20d1994c2f3719901e2d83ae8f6c3598cf00051d71b630633
