#app:
#  url:
#    _default: {{ .Chart.Name }}-{{ .Values.global.env }}.local
#    production: stat.mcn.ru
#    stage: stat.ks8.mcn.local

php_prod:
  error_reporting: 22517
  display_errors: On
  display_startup_errors: On
  enable_dl: Off
  log_errors: On
  error_log: /var/log/php.error.log
  report_memleaks: On
  variables_order: GPCS
  request_order: GP
  date:
    timezone: Europe/Moscow
  session:
    save_path: /var/lib/php/session
    gc_maxlifetime: 14400
    gc_probability: 1

php_fpm_prod:
  listen:
    #to: 0.0.0.0:9000
    to: 9000
    allowed_clients: 127.0.0.1
    owner: www-data
    group: www-data
    mode: 0660
  user: www-data
  group: www-data
  pm:
    type: dynamic
    max_children: 50
    start_servers: 5
    min_spare_servers: 5
    max_spare_servers: 35
    max_requests: 500

redis_prod:
  host: redis-prod
  port: 6379

graphql_prod:
  host: graphql-prod
  path: /graphql-hasura
  port: 8080
  enable_console: "true"

cryptopro_prod:
  host: cryptopro-prod
  port: 22

logger:
  source: stat

ci_url: stat.ks8.mcn.local
ci_dir_home: /home/httpd/stat.mcn.ru

use_ngnix_virtualserver: "no"
use_network_polices: "no"
use_minikube: "yes"

node_comet_prod:
  host: node-comet-prod
  path: /comet
  port: 3000
  logLevel: 200

node_nnp_ported_prod:
  host: node-nnp-ported-prod
  path: /nnp-ported
  port: 3001
  logLevel: 200

mysql_dev:
  host: mysqldb
  port: 3306
  user: root
  password: stat
  db: nispd

postgres_dev:
  host: history-db
  port: 5432
  user: postgres
  password: qwe123
  app_user: stat
  app_password: stat
  dbname: stat

params_prod:
  robocall_internal_server: https://robocall.mcn.ru
  calltracking_server: feedback.mcn.ru
  api_mcn_server: https://api.mcn.ru/v2/rest

params_dev:
  robocall_internal_server: 
  calltracking_server:
  api_mcn_server: