#app:
#  url:
#    _default: {{ .Chart.Name }}-{{ .Values.global.env }}.local
#    production: stat.mcn.ru
#    stage: stat.ks8.mcn.local

php_prod:
  error_reporting: 22517
  display_errors: On
  display_startup_errors: On
  enable_dl: Off
  log_errors: On
  error_log: /var/log/php.error.log
  report_memleaks: On
  variables_order: GPCS
  request_order: GP
  date:
    timezone: Europe/Moscow
  session:
    save_path: /var/lib/php/session
    gc_maxlifetime: 43200
    gc_probability: 1

php_fpm_prod:
  listen:
    #to: 0.0.0.0:9000
    to: 9000
    allowed_clients: 127.0.0.1
    owner: www-data
    group: www-data
    mode: 0660
  user: www-data
  group: www-data
  pm:
    type: dynamic
    max_children: 50
    start_servers: 5
    min_spare_servers: 5
    max_spare_servers: 35
    max_requests: 500

redis_prod:
  host: redis-prod
  port: 6379

graphql_prod:
  host: graphql-prod
  path: /graphql-hasura
  port: 8080
  enable_console: "true"

cryptopro_prod:
  host: cryptopro-prod
  port: 22

web_hook_dev:
  secret_key: "1122334455"
  token: "5544332211"
  account_id: 47197
  vpbx_id: 280

logger_dev:
  source: stat_dev
  server: glogstat.mcn.ru

logger_prod:
  source: stat
  server: glogstat.mcn.ru

logger_prod_eu:
  source: stat
  server: graylog.kompaas.tech

ci_url: stat.ks8.mcn.local
ci_dir_home: /home/httpd/stat.mcn.ru

use_ngnix_virtualserver: "no"
use_network_polices: "no"
use_minikube: "yes"

redis_server_dev:
  is_standalone: 1

redis_server_prod:
  is_standalone: 1
  sentineles: 3
  replicas: 3
  haproxies: 2

node_comet_prod:
  host: node-comet-prod
  path: /comet
  port: 3000
  logLevel: 200

node_balance:
  host: node-balance
  path: /balance
  port: 3003
  outPort: 30003
  logLevel: 200

node_nnp_ported_prod:
  host: node-nnp-ported-prod
  path: /nnp-ported
  port: 3001
  logLevel: 200

mysql_dev:
  host: mysqldb
  host_slave: mysqldb-slave
  port: 3306
  user: root
  password: stat
  db: nispd
  db_nfdump: nfdump

postgres_dev:
  host: iberus.mcn.ru
  host_slave: iberus.mcn.ru
  host_statistics: eridanus2.mcn.ru
  port: 5432
  app_user: stat
  app_password: stat
  db: nispd
  db_nfdump: nfdump

postgres_history_dev:
  host: postgres-history-dev
  db: stat
  user: postgres
  password:
  app_user: stat
  app_password: stat
  port: 5432


params_prod:
  robocall_internal_server: https://robocall.mcn.ru
  calltracking_server: feedback.mcn.ru
  feedback_server: feedback.mcn.ru
  api_mcn_server: https://api.mcn.ru/v2/rest
  phone_server: vpbx.mcn.ru
  core_server: lk.mcn.ru
  base_server: base.mcn.ru
  sync1c_ut_soap_url: http://stat.ws.dionis.mcn.ru/ws/ws/stat
  vps_is_enabled: "1"
  atol_is_enabled: "1"
  tele2_is_enabled: "1"
  async_is_enabled: "1"
  sberbank_api_is_enabled: "1"
  yandex_kassa_is_enabled: "1"
  mchs_is_enabled: "1"
  client_changed_amq_settings: "0"

params_prod_eu:
  robocall_internal_server: https://robocall.kompaas.tech
  calltracking_server: feedback.kompaas.tech
  feedback_server: feedback.kompaas.tech
  api_mcn_server: https://api.kompaas.tech/v2/rest
  phone_server: vpbx.kompaas.tech
  core_server: lk.kompaas.tech
  base_server: base.kompaas.tech
  sync1c_ut_soap_url:
  vps_is_enabled: "0"
  atol_is_enabled: "0"
  tele2_is_enabled: "0"
  async_is_enabled: "0"
  sberbank_api_is_enabled: "1"
  yandex_kassa_is_enabled: "0"
  mchs_is_enabled: "0"
  client_changed_amq_settings: "0"
  vmonitor:
    key1:
    key2:

params_dev:
  robocall_internal_server: 
  calltracking_server:
  api_mcn_server:
  phone_server:
  core_server:
  base_server:
  sync1c_ut_soap_url:
  api_secure_key: 111
  vps_is_enabled: "0"
  atol_is_enabled: "0"
  tele2_is_enabled: "0"
  async_is_enabled: "0"
  sberbank_api_is_enabled: "0"
  yandex_kassa_is_enabled: "0"
  mchs_is_enabled: "0"
  mchs_api_key:
  client_changed_amq_settings: "0"
  sms_gate:
    client: "xxx"
    password: "xxx"
    server: http://thiamis.mcn.ru/sms/gateway.php
  mailer:
    smtp:
      server: mail.xxx1.yyy2.zzz3.com
  vmonitor:
    key1:
    key2:


